
import path from 'path';
import { ParsedKnowledge } from './markdownParser';
import knowledgeData from '../../data/knowledge_base.json';

class KnowledgeService {
    private static instance: KnowledgeService;
    private knowledge: ParsedKnowledge[] = [];
    private lastLoaded: number = 0;
    // Cache TTL is less relevant now as we load from JSON, but we keep the structure
    // In a real app, 'import' caches the JSON module once.
    // If we want hot-reload of JSON without restart, we might need fs.readFileSync again on the JSON file.
    // For now, static import is fine and fastest.

    private constructor() {
        this.loadKnowledge();
    }

    public static getInstance(): KnowledgeService {
        if (!KnowledgeService.instance) {
            KnowledgeService.instance = new KnowledgeService();
        }
        return KnowledgeService.instance;
    }

    private loadKnowledge() {
        // Load from static JSON asset generated by sync engine
        this.knowledge = knowledgeData as ParsedKnowledge[];
        this.lastLoaded = Date.now();
        console.log(`[KnowledgeService] Loaded ${this.knowledge.length} knowledge items from static JSON.`);
    }

    private ensureFresh() {
        // No-op for static JSON import
    }

    public getAllKnowledge(): ParsedKnowledge[] {
        this.ensureFresh();
        return this.knowledge;
    }

    public getKnowledgeByStationId(stationId: string): ParsedKnowledge[] {
        this.ensureFresh();
        // Normalize ID for matching (handle odpt.Station vs odpt:Station)
        const normalizedId = stationId.replace(/\./g, ':');
        return this.knowledge
            .filter(k =>
                k.entityIds.includes('global') || // Include global items
                k.entityIds.some(id => id.replace(/\./g, ':') === normalizedId)
            )
            .sort((a, b) => b.priority - a.priority); // High priority first
    }

    public getKnowledgeByRailwayId(railwayId: string): ParsedKnowledge[] {
        this.ensureFresh();
        // Normalize ID
        const normalizedId = railwayId.replace(/\./g, ':');
        return this.knowledge
            .filter(k =>
                k.entityIds.some(id => id.replace(/\./g, ':') === normalizedId)
            )
            .sort((a, b) => b.priority - a.priority); // High priority first
    }

    public getKnowledgeByType(type: string): ParsedKnowledge[] {
        this.ensureFresh();
        return this.knowledge.filter(k => k.type === type);
    }
}

export const knowledgeService = KnowledgeService.getInstance();
