openapi: 3.0.0
info:
  title: LUTAGU Backend Tools
  description: Real-time data APIs for LUTAGU Dify Agent
  version: 1.0.0
servers:
  - url: https://lutagu-mvp.vercel.app
paths:
  /api/weather/live:
    get:
      operationId: get_weather
      summary: Get Tokyo Real-time Weather
      description: Returns current weather condition and temperature in Tokyo.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  weather:
                    type: string
                  temp:
                    type: number
  /api/odpt/train-status:
    get:
      operationId: get_train_status
      summary: Get Train Operation Status
      description: Returns delay and suspension information for major Tokyo train lines.
      responses:
        '200':
          description: Successful response
  /api/station/accessibility:
    get:
      operationId: get_accessibility
      summary: Get Station Accessibility Stats
      description: Returns barrier-free facility coverage (elevators, S-rank paths) for a specific station.
      parameters:
        - name: station_id
          in: query
          required: true
          description: The ODPT Station ID (e.g., odpt:Station:TokyoMetro.Ginza.Ueno)
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  elevator_coverage_percent:
                    type: integer
                  s_rank_paths:
                    type: integer
  /api/station/{station_id}/facilities:
    get:
      operationId: get_station_facilities
      summary: Get Station Facility Details (L3)
      description: Returns a list of specific facilities (toilets, elevators, exits) and their locations within the station. Use this to find specific elevator exits.
      parameters:
        - name: station_id
          in: path
          required: true
          description: The ODPT Station ID (e.g., odpt:Station:TokyoMetro.Ginza.Ueno)
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  stationId:
                    type: string
                  facilities:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                        location:
                          type: object
                        attributes:
                          type: object
  /api/util/time:
    get:
      operationId: get_japan_time
      summary: Get Current Japan Time (JST)
      description: Returns the current date, time, and period (e.g., morning_rush, late_night) in Tokyo. Use this to check if user is travelling during rush hour or if trains might be ending.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  jst_time:
                    type: string
                    description: Human readable time string
                  hour_jst:
                    type: integer
                  period:
                    type: string
                    description: Context (morning_rush, evening_rush, day, late_night)
                  day_of_week:
                    type: string
  /api/odpt/fare:
    get:
      operationId: get_fare
      summary: Get Train Fare (Ticket & IC)
      description: Returns the fare (Ticket and IC card) between two stations using structured ODPT data. Use this when user asks about price or cost.
      parameters:
        - name: from
          in: query
          required: true
          description: Origin Station ID (e.g., odpt:Station:TokyoMetro.Ginza.Ueno)
          schema:
            type: string
        - name: to
          in: query
          required: true
          description: Destination Station ID
          schema:
            type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  found:
                    type: boolean
                  fares:
                    type: array
                    items:
                      type: object
                      properties:
                        ticket:
                          type: integer
                        ic:
                          type: integer
                        operator:
                          type: string

  /api/odpt/timetable:
    get:
      operationId: get_timetable
      summary: Get Next Train Departures
      description: Returns the next 3 departures for each direction from the station. Use this when user asks "When is the next train?".
      parameters:
        - name: station
          in: query
          required: true
          description: Station ID (e.g., odpt:Station:TokyoMetro.Ginza.Ueno)
          schema:
            type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  station:
                    type: string
                  directions:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: object
                        properties:
                          time:
                            type: string
                          dest:
                            type: string
