
import fs from 'fs';
import path from 'path';

// Simplified Station Data for MVP
const LINES = [
    {
        id: 'odpt.Railway:JR-East.Yamanote',
        operator: 'odpt.Operator:JR-East',
        title: { ja: '山手線', en: 'Yamanote Line', 'zh-TW': '山手線' },
        stations: [
            'odpt.Station:JR-East.Yamanote.Tokyo',
            'odpt.Station:JR-East.Yamanote.Kanda',
            'odpt.Station:JR-East.Yamanote.Akihabara',
            'odpt.Station:JR-East.Yamanote.Okachimachi',
            'odpt.Station:JR-East.Yamanote.Ueno',
            'odpt.Station:JR-East.Yamanote.Uguisudani',
            'odpt.Station:JR-East.Yamanote.Nippori',
            'odpt.Station:JR-East.Yamanote.NishiNippori',
            'odpt.Station:JR-East.Yamanote.Tabata',
            'odpt.Station:JR-East.Yamanote.Komagome',
            'odpt.Station:JR-East.Yamanote.Sugamo',
            'odpt.Station:JR-East.Yamanote.Otsuka',
            'odpt.Station:JR-East.Yamanote.Ikebukuro',
            'odpt.Station:JR-East.Yamanote.Mejiro',
            'odpt.Station:JR-East.Yamanote.Takadanobaba',
            'odpt.Station:JR-East.Yamanote.ShinOkubo',
            'odpt.Station:JR-East.Yamanote.Shinjuku',
            'odpt.Station:JR-East.Yamanote.Yoyogi',
            'odpt.Station:JR-East.Yamanote.Harajuku',
            'odpt.Station:JR-East.Yamanote.Shibuya',
            'odpt.Station:JR-East.Yamanote.Ebisu',
            'odpt.Station:JR-East.Yamanote.Meguro',
            'odpt.Station:JR-East.Yamanote.Gotanda',
            'odpt.Station:JR-East.Yamanote.Osaki',
            'odpt.Station:JR-East.Yamanote.Shinagawa',
            'odpt.Station:JR-East.Yamanote.TakanawaGateway',
            'odpt.Station:JR-East.Yamanote.Tamachi',
            'odpt.Station:JR-East.Yamanote.Hamamatsucho',
            'odpt.Station:JR-East.Yamanote.Shimbashi',
            'odpt.Station:JR-East.Yamanote.Yurakucho',
            'odpt.Station:JR-East.Yamanote.Tokyo' // Loop closed
        ]
    },
    {
        id: 'odpt.Railway:TokyoMetro.Ginza',
        operator: 'odpt.Operator:TokyoMetro',
        title: { ja: '銀座線', en: 'Ginza Line', 'zh-TW': '銀座線' },
        stations: [
            'odpt.Station:TokyoMetro.Ginza.Shibuya',
            'odpt.Station:TokyoMetro.Ginza.Omotesando',
            'odpt.Station:TokyoMetro.Ginza.Gaiemmae',
            'odpt.Station:TokyoMetro.Ginza.AoyamaItchome',
            'odpt.Station:TokyoMetro.Ginza.AkasakaMitsuke',
            'odpt.Station:TokyoMetro.Ginza.TameikeSanno',
            'odpt.Station:TokyoMetro.Ginza.Toranomon',
            'odpt.Station:TokyoMetro.Ginza.Shimbashi',
            'odpt.Station:TokyoMetro.Ginza.Ginza',
            'odpt.Station:TokyoMetro.Ginza.Kyobashi',
            'odpt.Station:TokyoMetro.Ginza.Nihombashi',
            'odpt.Station:TokyoMetro.Ginza.Mitsukoshimae',
            'odpt.Station:TokyoMetro.Ginza.Kanda',
            'odpt.Station:TokyoMetro.Ginza.Suehirocho',
            'odpt.Station:TokyoMetro.Ginza.UenoHirokoji',
            'odpt.Station:TokyoMetro.Ginza.Ueno',
            'odpt.Station:TokyoMetro.Ginza.Inaricho',
            'odpt.Station:TokyoMetro.Ginza.Tawaramachi',
            'odpt.Station:TokyoMetro.Ginza.Asakusa'
        ]
    },
    {
        id: 'odpt.Railway:JR-East.KeihinTohoku',
        operator: 'odpt.Operator:JR-East',
        title: { ja: '京浜東北線', en: 'Keihin-Tohoku Line', 'zh-TW': '京濱東北線' },
        stations: [
            'odpt.Station:JR-East.KeihinTohoku.Omiya',
            'odpt.Station:JR-East.KeihinTohoku.SaitamaShintoshin',
            'odpt.Station:JR-East.KeihinTohoku.Yono',
            'odpt.Station:JR-East.KeihinTohoku.KitaUrawa',
            'odpt.Station:JR-East.KeihinTohoku.Urawa',
            'odpt.Station:JR-East.KeihinTohoku.MinamiUrawa',
            'odpt.Station:JR-East.KeihinTohoku.Warabi',
            'odpt.Station:JR-East.KeihinTohoku.NishiKawaguchi',
            'odpt.Station:JR-East.KeihinTohoku.Kawaguchi',
            'odpt.Station:JR-East.KeihinTohoku.Akabane',
            'odpt.Station:JR-East.KeihinTohoku.HigashiJujo',
            'odpt.Station:JR-East.KeihinTohoku.Oji',
            'odpt.Station:JR-East.KeihinTohoku.KamiNakazato',
            'odpt.Station:JR-East.KeihinTohoku.Tabata',
            'odpt.Station:JR-East.KeihinTohoku.NishiNippori',
            'odpt.Station:JR-East.KeihinTohoku.Nippori',
            'odpt.Station:JR-East.KeihinTohoku.Uguisudani',
            'odpt.Station:JR-East.KeihinTohoku.Ueno',
            'odpt.Station:JR-East.KeihinTohoku.Okachimachi',
            'odpt.Station:JR-East.KeihinTohoku.Akihabara',
            'odpt.Station:JR-East.KeihinTohoku.Kanda',
            'odpt.Station:JR-East.KeihinTohoku.Tokyo',
            'odpt.Station:JR-East.KeihinTohoku.Yurakucho',
            'odpt.Station:JR-East.KeihinTohoku.Shimbashi',
            'odpt.Station:JR-East.KeihinTohoku.Hamamatsucho',
            'odpt.Station:JR-East.KeihinTohoku.Tamachi',
            'odpt.Station:JR-East.KeihinTohoku.TakanawaGateway',
            'odpt.Station:JR-East.KeihinTohoku.Shinagawa',
            'odpt.Station:JR-East.KeihinTohoku.Oimachi',
            'odpt.Station:JR-East.KeihinTohoku.Omori',
            'odpt.Station:JR-East.KeihinTohoku.Kamata'
        ]
    },
    {
        id: 'odpt.Railway:TokyoMetro.Marunouchi',
        operator: 'odpt.Operator:TokyoMetro',
        title: { ja: '丸ノ内線', en: 'Marunouchi Line', 'zh-TW': '丸之內線' },
        stations: [
            'odpt.Station:TokyoMetro.Marunouchi.Ogikubo',
            'odpt.Station:TokyoMetro.Marunouchi.MinamiAsagaya',
            'odpt.Station:TokyoMetro.Marunouchi.ShinKoenji',
            'odpt.Station:TokyoMetro.Marunouchi.HigashiKoenji',
            'odpt.Station:TokyoMetro.Marunouchi.ShinNakano',
            'odpt.Station:TokyoMetro.Marunouchi.NakanoSakaue',
            'odpt.Station:TokyoMetro.Marunouchi.NishiShinjuku',
            'odpt.Station:TokyoMetro.Marunouchi.Shinjuku',
            'odpt.Station:TokyoMetro.Marunouchi.ShinjukuSanchome',
            'odpt.Station:TokyoMetro.Marunouchi.ShinjukuGyoemmae',
            'odpt.Station:TokyoMetro.Marunouchi.YotsuyaSanchome',
            'odpt.Station:TokyoMetro.Marunouchi.Yotsuya',
            'odpt.Station:TokyoMetro.Marunouchi.AkasakaMitsuke',
            'odpt.Station:TokyoMetro.Marunouchi.KokkaiGijidomae',
            'odpt.Station:TokyoMetro.Marunouchi.Kasumigaseki',
            'odpt.Station:TokyoMetro.Marunouchi.Ginza',
            'odpt.Station:TokyoMetro.Marunouchi.Tokyo',
            'odpt.Station:TokyoMetro.Marunouchi.Otemachi',
            'odpt.Station:TokyoMetro.Marunouchi.Awajicho',
            'odpt.Station:TokyoMetro.Marunouchi.Ochanomizu',
            'odpt.Station:TokyoMetro.Marunouchi.HongoSanchome',
            'odpt.Station:TokyoMetro.Marunouchi.Korakuen',
            'odpt.Station:TokyoMetro.Marunouchi.Myogadani',
            'odpt.Station:TokyoMetro.Marunouchi.ShinOtsuka',
            'odpt.Station:TokyoMetro.Marunouchi.Ikebukuro'
        ]
    },
    {
        id: 'odpt.Railway:TokyoMetro.Hibiya',
        operator: 'odpt.Operator:TokyoMetro',
        title: { ja: '日比谷線', en: 'Hibiya Line', 'zh-TW': '日比谷線' },
        stations: [
            'odpt.Station:TokyoMetro.Hibiya.NakaMeguro',
            'odpt.Station:TokyoMetro.Hibiya.Ebisu',
            'odpt.Station:TokyoMetro.Hibiya.Hiroo',
            'odpt.Station:TokyoMetro.Hibiya.Roppongi',
            'odpt.Station:TokyoMetro.Hibiya.Kamiyacho',
            'odpt.Station:TokyoMetro.Hibiya.ToranomonHills',
            'odpt.Station:TokyoMetro.Hibiya.Kasumigaseki',
            'odpt.Station:TokyoMetro.Hibiya.Hibiya',
            'odpt.Station:TokyoMetro.Hibiya.Ginza',
            'odpt.Station:TokyoMetro.Hibiya.HigashiGinza',
            'odpt.Station:TokyoMetro.Hibiya.Tsukiji',
            'odpt.Station:TokyoMetro.Hibiya.Hatchobori',
            'odpt.Station:TokyoMetro.Hibiya.Kayabacho',
            'odpt.Station:TokyoMetro.Hibiya.Ningyocho',
            'odpt.Station:TokyoMetro.Hibiya.Kodemmacho',
            'odpt.Station:TokyoMetro.Hibiya.Akihabara',
            'odpt.Station:TokyoMetro.Hibiya.NakaOkachimachi',
            'odpt.Station:TokyoMetro.Hibiya.Ueno',
            'odpt.Station:TokyoMetro.Hibiya.Iriya',
            'odpt.Station:TokyoMetro.Hibiya.Minowa',
            'odpt.Station:TokyoMetro.Hibiya.MinamiSenju',
            'odpt.Station:TokyoMetro.Hibiya.KitaSenju'
        ]
    },
    {
        id: 'odpt.Railway:JR-East.ChuoSobuLocal',
        operator: 'odpt.Operator:JR-East',
        title: { ja: '中央・総武線各駅停車', en: 'Chuo-Sobu Line (Local)', 'zh-TW': '中央・總武線（各站停車）' },
        stations: [
            'odpt.Station:JR-East.ChuoSobuLocal.Mitaka',
            'odpt.Station:JR-East.ChuoSobuLocal.Kichijoji',
            'odpt.Station:JR-East.ChuoSobuLocal.NishiOgikubo',
            'odpt.Station:JR-East.ChuoSobuLocal.Ogikubo',
            'odpt.Station:JR-East.ChuoSobuLocal.Asagaya',
            'odpt.Station:JR-East.ChuoSobuLocal.Koenji',
            'odpt.Station:JR-East.ChuoSobuLocal.Nakano',
            'odpt.Station:JR-East.ChuoSobuLocal.HigashiNakano',
            'odpt.Station:JR-East.ChuoSobuLocal.Okubo',
            'odpt.Station:JR-East.ChuoSobuLocal.Shinjuku',
            'odpt.Station:JR-East.ChuoSobuLocal.Yoyogi',
            'odpt.Station:JR-East.ChuoSobuLocal.Sendagaya',
            'odpt.Station:JR-East.ChuoSobuLocal.Shinanomachi',
            'odpt.Station:JR-East.ChuoSobuLocal.Yotsuya',
            'odpt.Station:JR-East.ChuoSobuLocal.Ichigaya',
            'odpt.Station:JR-East.ChuoSobuLocal.Iidabashi',
            'odpt.Station:JR-East.ChuoSobuLocal.Suidobashi',
            'odpt.Station:JR-East.ChuoSobuLocal.Ochanomizu',
            'odpt.Station:JR-East.ChuoSobuLocal.Akihabara',
            'odpt.Station:JR-East.ChuoSobuLocal.Asakusabashi',
            'odpt.Station:JR-East.ChuoSobuLocal.Ryogoku',
            'odpt.Station:JR-East.ChuoSobuLocal.Kinshicho',
            'odpt.Station:JR-East.ChuoSobuLocal.Kameido',
            'odpt.Station:JR-East.ChuoSobuLocal.Hirai',
            'odpt.Station:JR-East.ChuoSobuLocal.ShinKoiwa',
            'odpt.Station:JR-East.ChuoSobuLocal.Koiwa',
            'odpt.Station:JR-East.ChuoSobuLocal.Ichikawa',
            'odpt.Station:JR-East.ChuoSobuLocal.MotoYawata',
            'odpt.Station:JR-East.ChuoSobuLocal.ShimosaNakayama',
            'odpt.Station:JR-East.ChuoSobuLocal.NishiFunabashi',
            'odpt.Station:JR-East.ChuoSobuLocal.Funabashi',
            'odpt.Station:JR-East.ChuoSobuLocal.HigashiFunabashi',
            'odpt.Station:JR-East.ChuoSobuLocal.Tsudanuma',
            'odpt.Station:JR-East.ChuoSobuLocal.MakuhariHongo',
            'odpt.Station:JR-East.ChuoSobuLocal.Makuhari',
            'odpt.Station:JR-East.ChuoSobuLocal.ShinKemigawa',
            'odpt.Station:JR-East.ChuoSobuLocal.Inage',
            'odpt.Station:JR-East.ChuoSobuLocal.NishiChiba',
            'odpt.Station:JR-East.ChuoSobuLocal.Chiba'
        ]
    },
    {
        id: 'odpt.Railway:TokyoMetro.Chiyoda',
        operator: 'odpt.Operator:TokyoMetro',
        title: { ja: '千代田線', en: 'Chiyoda Line', 'zh-TW': '千代田線' },
        stations: [
            'odpt.Station:TokyoMetro.Chiyoda.YoyogiUehara',
            'odpt.Station:TokyoMetro.Chiyoda.YoyogiKoen',
            'odpt.Station:TokyoMetro.Chiyoda.MeijiJingumae',
            'odpt.Station:TokyoMetro.Chiyoda.Omotesando',
            'odpt.Station:TokyoMetro.Chiyoda.Nogizaka',
            'odpt.Station:TokyoMetro.Chiyoda.Akasaka',
            'odpt.Station:TokyoMetro.Chiyoda.KokkaiGijidomae',
            'odpt.Station:TokyoMetro.Chiyoda.Kasumigaseki',
            'odpt.Station:TokyoMetro.Chiyoda.Hibiya',
            'odpt.Station:TokyoMetro.Chiyoda.Nijubashimae',
            'odpt.Station:TokyoMetro.Chiyoda.Otemachi',
            'odpt.Station:TokyoMetro.Chiyoda.ShinOchanomizu',
            'odpt.Station:TokyoMetro.Chiyoda.Yushima',
            'odpt.Station:TokyoMetro.Chiyoda.Nezu',
            'odpt.Station:TokyoMetro.Chiyoda.Sendagi',
            'odpt.Station:TokyoMetro.Chiyoda.NishiNippori',
            'odpt.Station:TokyoMetro.Chiyoda.Machiya',
            'odpt.Station:TokyoMetro.Chiyoda.KitaSenju',
            'odpt.Station:TokyoMetro.Chiyoda.Ayase',
            'odpt.Station:TokyoMetro.Chiyoda.KitaAyase'
        ]
    },
    {
        id: 'odpt.Railway:TokyoMetro.Tozai',
        operator: 'odpt.Operator:TokyoMetro',
        title: { ja: '東西線', en: 'Tozai Line', 'zh-TW': '東西線' },
        stations: [
            'odpt.Station:TokyoMetro.Tozai.Nakano',
            'odpt.Station:TokyoMetro.Tozai.Ochiai',
            'odpt.Station:TokyoMetro.Tozai.Takadanobaba',
            'odpt.Station:TokyoMetro.Tozai.Waseda',
            'odpt.Station:TokyoMetro.Tozai.Kagurazaka',
            'odpt.Station:TokyoMetro.Tozai.Iidabashi',
            'odpt.Station:TokyoMetro.Tozai.Kudanshita',
            'odpt.Station:TokyoMetro.Tozai.Takebashi',
            'odpt.Station:TokyoMetro.Tozai.Otemachi',
            'odpt.Station:TokyoMetro.Tozai.Nihombashi',
            'odpt.Station:TokyoMetro.Tozai.Kayabacho',
            'odpt.Station:TokyoMetro.Tozai.MonzenNakacho',
            'odpt.Station:TokyoMetro.Tozai.Kiba',
            'odpt.Station:TokyoMetro.Tozai.Toyocho',
            'odpt.Station:TokyoMetro.Tozai.MinamiSunamachi',
            'odpt.Station:TokyoMetro.Tozai.NishiKasai',
            'odpt.Station:TokyoMetro.Tozai.Kasai',
            'odpt.Station:TokyoMetro.Tozai.Urayasu',
            'odpt.Station:TokyoMetro.Tozai.MinamiGyotoku',
            'odpt.Station:TokyoMetro.Tozai.Gyotoku',
            'odpt.Station:TokyoMetro.Tozai.Myoden',
            'odpt.Station:TokyoMetro.Tozai.BarakiNakayama',
            'odpt.Station:TokyoMetro.Tozai.NishiFunabashi'
        ]
    },
    {
        id: 'odpt.Railway:TokyoMetro.Namboku',
        operator: 'odpt.Operator:TokyoMetro',
        title: { ja: '南北線', en: 'Namboku Line', 'zh-TW': '南北線' },
        stations: [
            'odpt.Station:TokyoMetro.Namboku.Meguro',
            'odpt.Station:TokyoMetro.Namboku.Shirokanedai',
            'odpt.Station:TokyoMetro.Namboku.ShirokaneTakanawa',
            'odpt.Station:TokyoMetro.Namboku.AzabuJuban',
            'odpt.Station:TokyoMetro.Namboku.RoppongiItchome',
            'odpt.Station:TokyoMetro.Namboku.TameikeSanno',
            'odpt.Station:TokyoMetro.Namboku.Nagatacho',
            'odpt.Station:TokyoMetro.Namboku.Yotsuya',
            'odpt.Station:TokyoMetro.Namboku.Ichigaya',
            'odpt.Station:TokyoMetro.Namboku.Iidabashi',
            'odpt.Station:TokyoMetro.Namboku.Korakuen',
            'odpt.Station:TokyoMetro.Namboku.Todaimae',
            'odpt.Station:TokyoMetro.Namboku.HonKomagome',
            'odpt.Station:TokyoMetro.Namboku.Komagome',
            'odpt.Station:TokyoMetro.Namboku.Nishigahara',
            'odpt.Station:TokyoMetro.Namboku.Oji',
            'odpt.Station:TokyoMetro.Namboku.OjiKamiya',
            'odpt.Station:TokyoMetro.Namboku.Shimo',
            'odpt.Station:TokyoMetro.Namboku.AkabaneIwabuchi'
        ]
    },
    {
        id: 'odpt.Railway:TokyoMetro.Hanzomon',
        operator: 'odpt.Operator:TokyoMetro',
        title: { ja: '半蔵門線', en: 'Hanzomon Line', 'zh-TW': '半藏門線' },
        stations: [
            'odpt.Station:TokyoMetro.Hanzomon.Shibuya',
            'odpt.Station:TokyoMetro.Hanzomon.Omotesando',
            'odpt.Station:TokyoMetro.Hanzomon.AoyamaItchome',
            'odpt.Station:TokyoMetro.Hanzomon.Nagatacho',
            'odpt.Station:TokyoMetro.Hanzomon.Hanzomon',
            'odpt.Station:TokyoMetro.Hanzomon.Kudanshita',
            'odpt.Station:TokyoMetro.Hanzomon.Jimbocho',
            'odpt.Station:TokyoMetro.Hanzomon.Otemachi',
            'odpt.Station:TokyoMetro.Hanzomon.Mitsukoshimae',
            'odpt.Station:TokyoMetro.Hanzomon.Suitengumae',
            'odpt.Station:TokyoMetro.Hanzomon.KiyosumiShirakawa',
            'odpt.Station:TokyoMetro.Hanzomon.Sumiyoshi',
            'odpt.Station:TokyoMetro.Hanzomon.Kinshicho',
            'odpt.Station:TokyoMetro.Hanzomon.Oshiage'
        ]
    },
    {
        id: 'odpt.Railway:TokyoMetro.Yurakucho',
        operator: 'odpt.Operator:TokyoMetro',
        title: { ja: '有楽町線', en: 'Yurakucho Line', 'zh-TW': '有樂町線' },
        stations: [
            'odpt.Station:TokyoMetro.Yurakucho.Wakoshi',
            'odpt.Station:TokyoMetro.Yurakucho.ChikatetsuNarimasu',
            'odpt.Station:TokyoMetro.Yurakucho.ChikatetsuAkatsuka',
            'odpt.Station:TokyoMetro.Yurakucho.Heiwadai',
            'odpt.Station:TokyoMetro.Yurakucho.Hikawadai',
            'odpt.Station:TokyoMetro.Yurakucho.KotakeMukaihara',
            'odpt.Station:TokyoMetro.Yurakucho.Senkawa',
            'odpt.Station:TokyoMetro.Yurakucho.Kanamecho',
            'odpt.Station:TokyoMetro.Yurakucho.Ikebukuro',
            'odpt.Station:TokyoMetro.Yurakucho.HigashiIkebukuro',
            'odpt.Station:TokyoMetro.Yurakucho.Gokokuji',
            'odpt.Station:TokyoMetro.Yurakucho.Edogawabashi',
            'odpt.Station:TokyoMetro.Yurakucho.Iidabashi',
            'odpt.Station:TokyoMetro.Yurakucho.Ichigaya',
            'odpt.Station:TokyoMetro.Yurakucho.Kojimachi',
            'odpt.Station:TokyoMetro.Yurakucho.Nagatacho',
            'odpt.Station:TokyoMetro.Yurakucho.Sakuradamon',
            'odpt.Station:TokyoMetro.Yurakucho.Yurakucho',
            'odpt.Station:TokyoMetro.Yurakucho.GinzaItchome',
            'odpt.Station:TokyoMetro.Yurakucho.Shintomicho',
            'odpt.Station:TokyoMetro.Yurakucho.Tsukishima',
            'odpt.Station:TokyoMetro.Yurakucho.Toyosu',
            'odpt.Station:TokyoMetro.Yurakucho.Tatsumi',
            'odpt.Station:TokyoMetro.Yurakucho.ShinKiba'
        ]
    },
    {
        id: 'odpt.Railway:TokyoMetro.Fukutoshin',
        operator: 'odpt.Operator:TokyoMetro',
        title: { ja: '副都心線', en: 'Fukutoshin Line', 'zh-TW': '副都心線' },
        stations: [
            'odpt.Station:TokyoMetro.Fukutoshin.Wakoshi',
            'odpt.Station:TokyoMetro.Fukutoshin.ChikatetsuNarimasu',
            'odpt.Station:TokyoMetro.Fukutoshin.ChikatetsuAkatsuka',
            'odpt.Station:TokyoMetro.Fukutoshin.Heiwadai',
            'odpt.Station:TokyoMetro.Fukutoshin.Hikawadai',
            'odpt.Station:TokyoMetro.Fukutoshin.KotakeMukaihara',
            'odpt.Station:TokyoMetro.Fukutoshin.Senkawa',
            'odpt.Station:TokyoMetro.Fukutoshin.Kanamecho',
            'odpt.Station:TokyoMetro.Fukutoshin.Ikebukuro',
            'odpt.Station:TokyoMetro.Fukutoshin.Zoshigaya',
            'odpt.Station:TokyoMetro.Fukutoshin.NishiWaseda',
            'odpt.Station:TokyoMetro.Fukutoshin.HigashiShinjuku',
            'odpt.Station:TokyoMetro.Fukutoshin.ShinjukuSanchome',
            'odpt.Station:TokyoMetro.Fukutoshin.KitaSando',
            'odpt.Station:TokyoMetro.Fukutoshin.MeijiJingumae',
            'odpt.Station:TokyoMetro.Fukutoshin.Shibuya'
        ]
    }
];

function generate() {
    const topology = LINES.map(line => ({
        railwayId: line.id,
        operator: line.operator,
        title: line.title,
        stationOrder: line.stations.map((s, idx) => ({
            index: idx + 1,
            station: s,
            title: { en: s.split('.').pop(), ja: s.split('.').pop() } // Simplified titles
        }))
    }));

    const outputPath = path.join(process.cwd(), 'src/lib/l4/generated/coreTopology.json');
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    fs.writeFileSync(outputPath, JSON.stringify(topology, null, 2));
    console.log(`Generated topology with ${topology.length} lines to ${outputPath}`);
}

generate();
