-- L3 Data Expansion Migration (Generated at 2026-01-10T02:01:20.959Z)

-- Station: odpt:Station:TokyoMetro.Ginza (from odpt:Station:TokyoMetro.Ginza)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ginza', 'toilet', '{"ja":"Metro toilet","en":"Metro toilet"}'::jsonb, '{"hasWashlet":true,"wheelchair":true,"location_text":{"ja":"銀座四丁目交差點方面驗票口附近","en":"銀座四丁目交差點方面驗票口附近"},"floor":"Metro B1","operator":"Metro","source":"https://www.tokyometro.jp/lang_tcn/station/ginza/accessibility/","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ginza', 'toilet', '{"ja":"Metro toilet","en":"Metro toilet"}'::jsonb, '{"hasWashlet":true,"wheelchair":true,"location_text":{"ja":"C8 出口附近改札外 (新設)","en":"C8 出口附近改札外 (新設)"},"floor":"Metro B1","operator":"Metro","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ginza', 'locker', '{"ja":"Metro locker","en":"Metro locker"}'::jsonb, '{"count":30,"sizes":["S","M","L"],"location_text":{"ja":"有樂町方面驗票口外 右側通路","en":"有樂町方面驗票口外 右側通路"},"floor":"Metro B1","operator":"Metro","source":"https://coinlocker.click/ginza-station.php","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ginza', 'locker', '{"ja":"Metro locker","en":"Metro locker"}'::jsonb, '{"count":50,"sizes":["S","M","L"],"location_text":{"ja":"C5/C6 出口之間通路","en":"C5/C6 出口之間通路"},"floor":"Metro B1","operator":"Metro","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ginza', 'elevator', '{"ja":"Metro elevator","en":"Metro elevator"}'::jsonb, '{"wheelchair":true,"location_text":{"ja":"A7 出口 (銀座三越)","en":"A7 出口 (銀座三越)"},"floor":"Metro GF","operator":"Metro","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ginza', 'elevator', '{"ja":"Metro elevator","en":"Metro elevator"}'::jsonb, '{"wheelchair":true,"location_text":{"ja":"銀座線/丸之內線月台 → 穿堂層","en":"銀座線/丸之內線月台 → 穿堂層"},"floor":"Metro B1","operator":"Metro","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ginza', 'wifi', '{"ja":"Metro wifi","en":"Metro wifi"}'::jsonb, '{"ssid":"METRO_FREE_WiFi","location_text":{"ja":"改札內","en":"改札內"},"floor":"Metro GF","operator":"Metro","is_available":true}'::jsonb);
-- Station: odpt:Station:Toei.Nihombashi (from odpt:Station:Toei.Nihombashi)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Toei.Nihombashi', 'toilet', '{"ja":"Metro toilet","en":"Metro toilet"}'::jsonb, '{"hasWashlet":true,"wheelchair":true,"location_text":{"ja":"吳服橋方面驗票口內 (東西線側)","en":"吳服橋方面驗票口內 (東西線側)"},"floor":"Metro B1","operator":"Metro","source":"https://www.tokyometro.jp/lang_tcn/station/nihombashi/accessibility/","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Toei.Nihombashi', 'toilet', '{"ja":"Toei toilet","en":"Toei toilet"}'::jsonb, '{"hasWashlet":true,"wheelchair":true,"location_text":{"ja":"茅場町方面驗票口附近","en":"茅場町方面驗票口附近"},"floor":"Toei B1","operator":"Toei","source":"https://www.kotsu.metro.tokyo.jp/subway/stations/nihombashi.html","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Toei.Nihombashi', 'locker', '{"ja":"Metro locker","en":"Metro locker"}'::jsonb, '{"count":40,"sizes":["S","M","L"],"location_text":{"ja":"B0 出口向處 (高島屋方面)","en":"B0 出口向處 (高島屋方面)"},"floor":"Metro B1","operator":"Metro","source":"https://coin-locker.net/nihonbashi/","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Toei.Nihombashi', 'locker', '{"ja":"Toei locker","en":"Toei locker"}'::jsonb, '{"count":20,"sizes":["S","M"],"location_text":{"ja":"改札外 茅場町方面出口通路","en":"改札外 茅場町方面出口通路"},"floor":"Toei B1","operator":"Toei","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Toei.Nihombashi', 'elevator', '{"ja":"Metro elevator","en":"Metro elevator"}'::jsonb, '{"wheelchair":true,"location_text":{"ja":"B0 出口電梯","en":"B0 出口電梯"},"floor":"Metro GF","operator":"Metro","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Toei.Nihombashi', 'elevator', '{"ja":"Toei elevator","en":"Toei elevator"}'::jsonb, '{"wheelchair":true,"location_text":{"ja":"D1 出口電梯","en":"D1 出口電梯"},"floor":"Toei GF","operator":"Toei","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Toei.Nihombashi', 'wifi', '{"ja":"Metro wifi","en":"Metro wifi"}'::jsonb, '{"ssid":"METRO_FREE_WiFi","location_text":{"ja":"全站","en":"全站"},"floor":"Metro/Toei","operator":"Metro","is_available":true}'::jsonb);
-- Station: odpt:Station:TokyoMetro.Tawaramachi (from odpt:Station:TokyoMetro.Tawaramachi)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Tawaramachi', 'toilet', '{"ja":"Metro toilet","en":"Metro toilet"}'::jsonb, '{"wheelchair":true,"location_text":{"ja":"改札內","en":"改札內"},"floor":"Metro B1","operator":"Metro","source":"https://www.tokyometro.jp/lang_tcn/station/tawaramachi/accessibility/","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Tawaramachi', 'elevator', '{"ja":"Metro elevator","en":"Metro elevator"}'::jsonb, '{"note":"合羽橋方向推薦","wheelchair":true,"location_text":{"ja":"2號出口","en":"2號出口"},"floor":"Metro B1","operator":"Metro","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Tawaramachi', 'wifi', '{"ja":"Metro wifi","en":"Metro wifi"}'::jsonb, '{"ssid":"METRO_FREE_WiFi","location_text":{"ja":"改札內","en":"改札內"},"floor":"Metro B1","operator":"Metro","is_available":true}'::jsonb);
-- Station: odpt:Station:TokyoMetro.Ueno (from odpt:Station:TokyoMetro.Ueno)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ueno', 'toilet', '{"ja":"Metro toilet","en":"Metro toilet"}'::jsonb, '{"hasWashlet":true,"wheelchair":true,"location_text":{"ja":"銀座線 往JR方向驗票口內","en":"銀座線 往JR方向驗票口內"},"floor":"Metro B1","operator":"Metro","source":"https://www.tokyometro.jp/lang_tcn/station/ueno/accessibility/","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ueno', 'toilet', '{"ja":"Metro toilet","en":"Metro toilet"}'::jsonb, '{"hasWashlet":true,"wheelchair":true,"location_text":{"ja":"日比谷線 電梯專用出口驗票口外","en":"日比谷線 電梯專用出口驗票口外"},"floor":"Metro B1","operator":"Metro","source":"https://www.tokyometro.jp/lang_tcn/station/ueno/accessibility/","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ueno', 'toilet', '{"ja":"JR toilet","en":"JR toilet"}'::jsonb, '{"hasWashlet":true,"wheelchair":true,"location_text":{"ja":"大連絡橋通道","en":"大連絡橋通道"},"floor":"JR 3F","operator":"JR","source":"https://www.jreast.co.jp/estation/stations/204.html","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ueno', 'toilet', '{"ja":"JR toilet","en":"JR toilet"}'::jsonb, '{"note":"含育嬰室","hasWashlet":true,"wheelchair":true,"hasBabyRoom":true,"location_text":{"ja":"ecute Ueno 內","en":"ecute Ueno 內"},"floor":"JR 3F","operator":"JR","source":"https://www.jreast.co.jp/estation/stations/204.html","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ueno', 'locker', '{"ja":"JR locker","en":"JR locker"}'::jsonb, '{"note":"最大量置物櫃區","count":300,"sizes":["S","M","L","XL"],"location_text":{"ja":"中央口改札外","en":"中央口改札外"},"floor":"JR 1F","operator":"JR","source":"https://www.jreast.co.jp/estation/stations/204.html","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ueno', 'locker', '{"ja":"Metro locker","en":"Metro locker"}'::jsonb, '{"count":80,"sizes":["S","M","L"],"location_text":{"ja":"不忍口改札外","en":"不忍口改札外"},"floor":"Metro B1","operator":"Metro","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ueno', 'elevator', '{"ja":"Metro elevator","en":"Metro elevator"}'::jsonb, '{"wheelchair":true,"location_text":{"ja":"銀座線月台 → JR方向驗票口","en":"銀座線月台 → JR方向驗票口"},"floor":"Metro B1","operator":"Metro","source":"https://www.tokyometro.jp/lang_tcn/station/ueno/accessibility/","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ueno', 'elevator', '{"ja":"Metro elevator","en":"Metro elevator"}'::jsonb, '{"note":"通往上野公園","wheelchair":true,"location_text":{"ja":"公園驗票口 → 5a出口","en":"公園驗票口 → 5a出口"},"floor":"Metro B1","operator":"Metro","source":"https://www.tokyometro.jp/lang_tcn/station/ueno/accessibility/","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ueno', 'wifi', '{"ja":"Metro wifi","en":"Metro wifi"}'::jsonb, '{"note":"限時30分","ssid":"METRO_FREE_WiFi","location_text":{"ja":"改札內全區","en":"改札內全區"},"floor":"Metro 全層","operator":"Metro","is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ueno', 'charging', '{"ja":"JR charging","en":"JR charging"}'::jsonb, '{"note":"Type-A, Type-C 插座","location_text":{"ja":"ecute Ueno 咖啡廳","en":"ecute Ueno 咖啡廳"},"floor":"JR 3F","operator":"JR","is_available":true}'::jsonb);
-- Station: odpt:Station:JR-East.Akihabara (from odpt:Station:JR-East.Akihabara)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Akihabara', 'locker', '{"ja":"Locker","en":"Locker"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Akihabara', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Akihabara', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Akihabara', 'wifi', '{"ja":"Wifi","en":"Wifi"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
-- Station: odpt:Station:JR-East.Okachimachi (from odpt:Station:JR-East.Okachimachi)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Okachimachi', 'barrier_free_entrance', '{"ja":"Barrier_free_entrance","en":"Barrier_free_entrance"}'::jsonb, '{"stroller":true,"updated_at":"2025-12-28T10:35:01.925Z","wheelchair":true,"location_text":{"ja":"1F 南口","en":"1F 南口"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Okachimachi', 'elevator', '{"ja":"Elevator","en":"Elevator"}'::jsonb, '{"stroller":true,"updated_at":"2025-12-28T10:35:01.925Z","wheelchair":true,"location_text":{"ja":"1F改札〜2Fホーム","en":"1F改札〜2Fホーム"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Okachimachi', 'elevator', '{"ja":"Elevator","en":"Elevator"}'::jsonb, '{"stroller":true,"updated_at":"2025-12-28T10:35:01.925Z","wheelchair":true,"location_text":{"ja":"1F南口〜2Fホーム","en":"1F南口〜2Fホーム"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Okachimachi', 'escalator', '{"ja":"Escalator","en":"Escalator"}'::jsonb, '{"stroller":true,"updated_at":"2025-12-28T10:35:01.925Z","wheelchair":false,"location_text":{"ja":"1F改札〜2Fホーム","en":"1F改札〜2Fホーム"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Okachimachi', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"ostomate":true,"baby_chair":true,"updated_at":"2025-12-28T10:35:01.925Z","wheelchair":true,"diaper_changing_table":true,"location_text":{"ja":"2F ホーム","en":"2F ホーム"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Okachimachi', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"ostomate":false,"updated_at":"2025-12-28T10:35:01.925Z","wheelchair":false,"location_text":{"ja":"1F 改札内","en":"1F 改札内"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Okachimachi', 'ticket_gate', '{"ja":"Ticket_gate","en":"Ticket_gate"}'::jsonb, '{"wide_gate":true,"updated_at":"2025-12-28T10:35:01.925Z","wheelchair_accessible":true,"location_text":{"ja":"1F","en":"1F"},"is_available":true}'::jsonb);
-- Station: odpt:Station:JR-East.Kanda (from odpt:Station:JR-East.Kanda)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Kanda', 'barrier_free_entrance', '{"ja":"Barrier_free_entrance","en":"Barrier_free_entrance"}'::jsonb, '{"updated_at":"2025-12-28T10:35:11.006Z","wheelchair_accessible":true,"location_text":{"ja":"1F","en":"1F"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Kanda', 'elevator', '{"ja":"Elevator","en":"Elevator"}'::jsonb, '{"updated_at":"2025-12-28T10:35:11.006Z","wheelchair":true,"location_text":{"ja":"1F改札〜2Fホーム","en":"1F改札〜2Fホーム"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Kanda', 'escalator', '{"ja":"Escalator","en":"Escalator"}'::jsonb, '{"updated_at":"2025-12-28T10:35:11.006Z","wheelchair":false,"location_text":{"ja":"1F改札〜2Fホーム","en":"1F改札〜2Fホーム"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Kanda', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"ostomate":true,"baby_chair":true,"updated_at":"2025-12-28T10:35:11.006Z","wheelchair":true,"location_text":{"ja":"1F","en":"1F"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Kanda', 'waiting_room', '{"ja":"Waiting_room","en":"Waiting_room"}'::jsonb, '{"updated_at":"2025-12-28T10:35:11.006Z","wheelchair_accessible":true,"location_text":{"ja":"2F","en":"2F"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Kanda', 'ticket_gate', '{"ja":"Ticket_gate","en":"Ticket_gate"}'::jsonb, '{"wide_gate":true,"updated_at":"2025-12-28T10:35:11.006Z","wheelchair_accessible":true,"location_text":{"ja":"1F","en":"1F"},"is_available":true}'::jsonb);
-- Station: odpt:Station:JR-East.Hatchobori (from odpt:Station:JR-East.Hatchobori)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Hatchobori', 'barrier_free_entrance', '{"ja":"Barrier_free_entrance","en":"Barrier_free_entrance"}'::jsonb, '{"updated_at":"2025-12-28T10:35:21.704Z","location_text":{"ja":"B3F - B2F - B1F - 1F","en":"B3F - B2F - B1F - 1F"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Hatchobori', 'elevator', '{"ja":"Elevator","en":"Elevator"}'::jsonb, '{"updated_at":"2025-12-28T10:35:21.704Z","wheelchair":true,"location_text":{"ja":"3F改札〜1Fホーム","en":"3F改札〜1Fホーム"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Hatchobori', 'elevator', '{"ja":"Elevator","en":"Elevator"}'::jsonb, '{"updated_at":"2025-12-28T10:35:21.704Z","wheelchair":true,"location_text":{"ja":"3F改札〜1Fホーム","en":"3F改札〜1Fホーム"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Hatchobori', 'escalator', '{"ja":"Escalator","en":"Escalator"}'::jsonb, '{"updated_at":"2025-12-28T10:35:21.704Z","location_text":{"ja":"3F改札〜1Fホーム","en":"3F改札〜1Fホーム"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Hatchobori', 'escalator', '{"ja":"Escalator","en":"Escalator"}'::jsonb, '{"updated_at":"2025-12-28T10:35:21.704Z","location_text":{"ja":"3F改札〜1Fホーム","en":"3F改札〜1Fホーム"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Hatchobori', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"ostomate":true,"baby_chair":true,"updated_at":"2025-12-28T10:35:21.704Z","wheelchair":true,"location_text":{"ja":"1Fホーム","en":"1Fホーム"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Hatchobori', 'ticket_gate', '{"ja":"Ticket_gate","en":"Ticket_gate"}'::jsonb, '{"wide_gate":true,"updated_at":"2025-12-28T10:35:21.704Z","location_text":{"ja":"3F","en":"3F"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Hatchobori', 'ticket_gate', '{"ja":"Ticket_gate","en":"Ticket_gate"}'::jsonb, '{"wide_gate":true,"updated_at":"2025-12-28T10:35:21.704Z","location_text":{"ja":"3F","en":"3F"},"is_available":true}'::jsonb);
-- Station: odpt:Station:JR-East.Uguisudani (from odpt:Station:JR-East.Uguisudani)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Uguisudani', 'barrier_free_entrance', '{"ja":"Barrier_free_entrance","en":"Barrier_free_entrance"}'::jsonb, '{"updated_at":"2025-12-28T10:35:31.279Z","location_text":{"ja":"1F 南口","en":"1F 南口"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Uguisudani', 'elevator', '{"ja":"Elevator","en":"Elevator"}'::jsonb, '{"updated_at":"2025-12-28T10:35:31.279Z","wheelchair":true,"location_text":{"ja":"3F改札〜1Fホーム","en":"3F改札〜1Fホーム"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Uguisudani', 'escalator', '{"ja":"Escalator","en":"Escalator"}'::jsonb, '{"updated_at":"2025-12-28T10:35:31.279Z","location_text":{"ja":"3F改札〜1Fホーム","en":"3F改札〜1Fホーム"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Uguisudani', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"ostomate":true,"baby_chair":true,"updated_at":"2025-12-28T10:35:31.279Z","wheelchair":true,"location_text":{"ja":"1F 改札内","en":"1F 改札内"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Uguisudani', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"updated_at":"2025-12-28T10:35:31.279Z","location_text":{"ja":"1F 改札内","en":"1F 改札内"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Uguisudani', 'waiting_room', '{"ja":"Waiting_room","en":"Waiting_room"}'::jsonb, '{"updated_at":"2025-12-28T10:35:31.279Z","wheelchair_accessible":true,"location_text":{"ja":"1F 改札内","en":"1F 改札内"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Uguisudani', 'ticket_gate', '{"ja":"Ticket_gate","en":"Ticket_gate"}'::jsonb, '{"wide_gate":true,"updated_at":"2025-12-28T10:35:31.279Z","location_text":{"ja":"3F","en":"3F"},"is_available":true}'::jsonb);
-- Station: odpt:Station:JR-East.Hamamatsucho (from odpt:Station:JR-East.Hamamatsucho)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Hamamatsucho', 'barrier_free_entrance', '{"ja":"Barrier_free_entrance","en":"Barrier_free_entrance"}'::jsonb, '{"updated_at":"2025-12-28T10:35:43.400Z","location_text":{"ja":"1F","en":"1F"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Hamamatsucho', 'elevator', '{"ja":"Elevator","en":"Elevator"}'::jsonb, '{"updated_at":"2025-12-28T10:35:43.400Z","wheelchair":true,"location_text":{"ja":"3F改札〜1Fホーム","en":"3F改札〜1Fホーム"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Hamamatsucho', 'elevator', '{"ja":"Elevator","en":"Elevator"}'::jsonb, '{"updated_at":"2025-12-28T10:35:43.400Z","wheelchair":true,"location_text":{"ja":"3F改札〜1Fホーム","en":"3F改札〜1Fホーム"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Hamamatsucho', 'escalator', '{"ja":"Escalator","en":"Escalator"}'::jsonb, '{"updated_at":"2025-12-28T10:35:43.400Z","location_text":{"ja":"3F改札〜1Fホーム","en":"3F改札〜1Fホーム"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Hamamatsucho', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"ostomate":true,"baby_chair":true,"updated_at":"2025-12-28T10:35:43.400Z","wheelchair":true,"location_text":{"ja":"1Fホーム","en":"1Fホーム"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Hamamatsucho', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"ostomate":true,"baby_chair":true,"updated_at":"2025-12-28T10:35:43.400Z","wheelchair":true,"location_text":{"ja":"3F改札内","en":"3F改札内"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Hamamatsucho', 'waiting_room', '{"ja":"Waiting_room","en":"Waiting_room"}'::jsonb, '{"updated_at":"2025-12-28T10:35:43.400Z","wheelchair_accessible":true,"location_text":{"ja":"3F改札内","en":"3F改札内"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Hamamatsucho', 'ticket_gate', '{"ja":"Ticket_gate","en":"Ticket_gate"}'::jsonb, '{"wide_gate":true,"updated_at":"2025-12-28T10:35:43.400Z","location_text":{"ja":"3F","en":"3F"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Hamamatsucho', 'ticket_gate', '{"ja":"Ticket_gate","en":"Ticket_gate"}'::jsonb, '{"wide_gate":true,"updated_at":"2025-12-28T10:35:43.400Z","location_text":{"ja":"3F","en":"3F"},"is_available":true}'::jsonb);
-- Station: odpt:Station:JR-East.Tokyo (from odpt:Station:JR-East.Tokyo)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Tokyo', 'locker', '{"ja":"Locker","en":"Locker"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Tokyo', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Tokyo', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Tokyo', 'wifi', '{"ja":"Wifi","en":"Wifi"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
-- Station: odpt:Station:JR-East.Ueno (from odpt:Station:JR-East.Ueno)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Ueno', 'locker', '{"ja":"Locker","en":"Locker"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Ueno', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Ueno', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Ueno', 'wifi', '{"ja":"Wifi","en":"Wifi"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
-- Station: odpt:Station:TokyoMetro.Oshiage (from odpt.Station:TokyoMetro.Hanzomon.Oshiage)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Oshiage', 'locker', '{"ja":"Locker","en":"Locker"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Oshiage', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Oshiage', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Oshiage', 'wifi', '{"ja":"Wifi","en":"Wifi"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
-- Station: odpt:Station:JR-East.Shinjuku (from odpt:Station:JR-East.Shinjuku)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Shinjuku', 'locker', '{"ja":"Locker","en":"Locker"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Shinjuku', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Shinjuku', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Shinjuku', 'wifi', '{"ja":"Wifi","en":"Wifi"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
-- Station: odpt:Station:JR-East.Shinagawa (from odpt.Station:JR-East.Yamanote.Shinagawa)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Shinagawa', 'locker', '{"ja":"Locker","en":"Locker"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Shinagawa', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Shinagawa', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Shinagawa', 'wifi', '{"ja":"Wifi","en":"Wifi"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
-- Station: odpt:Station:TokyoMetro.Ginza (from odpt.Station:TokyoMetro.Ginza.Ginza)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ginza', 'locker', '{"ja":"Locker","en":"Locker"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ginza', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ginza', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:TokyoMetro.Ginza', 'wifi', '{"ja":"Wifi","en":"Wifi"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
-- Station: odpt:Station:JR-East.Shimbashi (from odpt.Station:JR-East.Yamanote.Shimbashi)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Shimbashi', 'locker', '{"ja":"Locker","en":"Locker"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Shimbashi', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Shimbashi', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Shimbashi', 'wifi', '{"ja":"Wifi","en":"Wifi"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
-- Station: odpt:Station:JR-East.Shibuya (from odpt:Station:JR-East.Shibuya)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Shibuya', 'locker', '{"ja":"Locker","en":"Locker"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Shibuya', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Shibuya', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Shibuya', 'wifi', '{"ja":"Wifi","en":"Wifi"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
-- Station: odpt:Station:JR-East.Ikebukuro (from odpt:Station:JR-East.Ikebukuro)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Ikebukuro', 'locker', '{"ja":"Locker","en":"Locker"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Ikebukuro', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Ikebukuro', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:JR-East.Ikebukuro', 'wifi', '{"ja":"Wifi","en":"Wifi"}'::jsonb, '{"location_text":{"ja":"駅構内","en":"Inside Station"},"is_available":true}'::jsonb);
-- Station: odpt:Station:Airport.Haneda (from odpt:Station:Airport.Haneda)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"Terminal 1 2F Departure Lobby North","en":"Terminal 1 2F Departure Lobby North"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"Terminal 1 2F Departure Lobby Close to Gate 10 Departure Lounge","en":"Terminal 1 2F Departure Lobby Close to Gate 10 Departure Lounge"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"Terminal 1 1F Arrival Lobby North","en":"Terminal 1 1F Arrival Lobby North"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"Terminal 1 1F Market Place","en":"Terminal 1 1F Market Place"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"Terminal 1 B1F Marketplace","en":"Terminal 1 B1F Marketplace"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"Terminal 1 B1F Marketplace South","en":"Terminal 1 B1F Marketplace South"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"Terminal 1 B1F Marketplace North","en":"Terminal 1 B1F Marketplace North"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"Terminal 1 1F Arrival Lobby North","en":"Terminal 1 1F Arrival Lobby North"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"Terminal 1 2F Departure Lobby South","en":"Terminal 1 2F Departure Lobby South"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"Terminal 1 3F Terrace Restaurant South","en":"Terminal 1 3F Terrace Restaurant South"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"Terminal 1 1F Arrival Lobby North","en":"Terminal 1 1F Arrival Lobby North"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"Terminal 1 1F Arrival Lobby North","en":"Terminal 1 1F Arrival Lobby North"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"Terminal 1 1F Arrival Lobby North","en":"Terminal 1 1F Arrival Lobby North"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'coin_locker', '{"ja":"Coin_locker","en":"Coin_locker"}'::jsonb, '{"location_text":{"ja":"Terminal 1 B1F","en":"Terminal 1 B1F"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'coin_locker', '{"ja":"Coin_locker","en":"Coin_locker"}'::jsonb, '{"location_text":{"ja":"Terminal 1 1F, General Area (A)","en":"Terminal 1 1F, General Area (A)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'coin_locker', '{"ja":"Coin_locker","en":"Coin_locker"}'::jsonb, '{"location_text":{"ja":"Terminal 1 2F, General Area (C/D)","en":"Terminal 1 2F, General Area (C/D)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'coin_locker', '{"ja":"Coin_locker","en":"Coin_locker"}'::jsonb, '{"location_text":{"ja":"Terminal 1 2F, General Area (E/H)","en":"Terminal 1 2F, General Area (E/H)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'coin_locker', '{"ja":"Coin_locker","en":"Coin_locker"}'::jsonb, '{"location_text":{"ja":"Terminal 1 2F, General Area (F/G)","en":"Terminal 1 2F, General Area (F/G)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'charging_station', '{"ja":"Charging_station","en":"Charging_station"}'::jsonb, '{"location_text":{"ja":"Terminal 1 1F","en":"Terminal 1 1F"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'charging_station', '{"ja":"Charging_station","en":"Charging_station"}'::jsonb, '{"location_text":{"ja":"Terminal 2 (various locations)","en":"Terminal 2 (various locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'charging_station', '{"ja":"Charging_station","en":"Charging_station"}'::jsonb, '{"location_text":{"ja":"Terminal 3 (various locations)","en":"Terminal 3 (various locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'nursery', '{"ja":"Nursery","en":"Nursery"}'::jsonb, '{"location_text":{"ja":"Terminal 1 B1F, General Area (2 locations)","en":"Terminal 1 B1F, General Area (2 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'nursery', '{"ja":"Nursery","en":"Nursery"}'::jsonb, '{"location_text":{"ja":"Terminal 1 1F, General Area (4 locations)","en":"Terminal 1 1F, General Area (4 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'nursery', '{"ja":"Nursery","en":"Nursery"}'::jsonb, '{"location_text":{"ja":"Terminal 1 1F Bus Departure Lounge, Airside Area (For women only, 2 locations)","en":"Terminal 1 1F Bus Departure Lounge, Airside Area (For women only, 2 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'nursery', '{"ja":"Nursery","en":"Nursery"}'::jsonb, '{"location_text":{"ja":"Terminal 1 2F, General Area (4 locations)","en":"Terminal 1 2F, General Area (4 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'nursery', '{"ja":"Nursery","en":"Nursery"}'::jsonb, '{"location_text":{"ja":"Terminal 1 2F, Restricted Areas (2 locations)","en":"Terminal 1 2F, Restricted Areas (2 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'nursery', '{"ja":"Nursery","en":"Nursery"}'::jsonb, '{"location_text":{"ja":"Terminal 1 2F, Airside Area (For women only, 3 locations)","en":"Terminal 1 2F, Airside Area (For women only, 3 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"Terminal 1 B1F General Area (3 locations)","en":"Terminal 1 B1F General Area (3 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"Terminal 1 1F General Area (4 locations)","en":"Terminal 1 1F General Area (4 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"Terminal 1 1F Airside Area (2 locations)","en":"Terminal 1 1F Airside Area (2 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"Terminal 1 2F General Area (8 locations)","en":"Terminal 1 2F General Area (8 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"Terminal 1 2F Airside Area (12 locations)","en":"Terminal 1 2F Airside Area (12 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"Terminal 1 3F General Area (3 locations)","en":"Terminal 1 3F General Area (3 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"Terminal 1 4F General Area (1 location)","en":"Terminal 1 4F General Area (1 location)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"Terminal 1 5F General Area (2 locations)","en":"Terminal 1 5F General Area (2 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"Terminal 1 6F General Area (2 locations)","en":"Terminal 1 6F General Area (2 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"Terminal 1 B1F General Area (3 locations)","en":"Terminal 1 B1F General Area (3 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"Terminal 1 1F General Area (4 locations)","en":"Terminal 1 1F General Area (4 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"Terminal 1 1F Airside Area (2 locations)","en":"Terminal 1 1F Airside Area (2 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"Terminal 1 2F General Area (8 locations)","en":"Terminal 1 2F General Area (8 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"Terminal 1 2F Airside Area (12 locations)","en":"Terminal 1 2F Airside Area (12 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"Terminal 1 3F General Area (3 locations)","en":"Terminal 1 3F General Area (3 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"Terminal 1 4F General Area (1 location)","en":"Terminal 1 4F General Area (1 location)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"Terminal 1 5F General Area (2 locations)","en":"Terminal 1 5F General Area (2 locations)"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Haneda', 'toilet', '{"ja":"Toilet","en":"Toilet"}'::jsonb, '{"location_text":{"ja":"Terminal 1 6F General Area (2 locations)","en":"Terminal 1 6F General Area (2 locations)"},"is_available":true}'::jsonb);
-- Station: odpt:Station:Airport.Narita (from odpt:Station:Airport.Narita)
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Narita', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"Terminal 1","en":"Terminal 1"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Narita', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"Terminal 2","en":"Terminal 2"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Narita', 'atm', '{"ja":"Atm","en":"Atm"}'::jsonb, '{"location_text":{"ja":"Terminal 3","en":"Terminal 3"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Narita', 'coin_locker', '{"ja":"Coin_locker","en":"Coin_locker"}'::jsonb, '{"location_text":{"ja":"Terminal 1","en":"Terminal 1"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Narita', 'coin_locker', '{"ja":"Coin_locker","en":"Coin_locker"}'::jsonb, '{"location_text":{"ja":"Terminal 2","en":"Terminal 2"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Narita', 'coin_locker', '{"ja":"Coin_locker","en":"Coin_locker"}'::jsonb, '{"location_text":{"ja":"Terminal 3","en":"Terminal 3"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Narita', 'clinic', '{"ja":"Clinic","en":"Clinic"}'::jsonb, '{"location_text":{"ja":"Terminal 1","en":"Terminal 1"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Narita', 'clinic', '{"ja":"Clinic","en":"Clinic"}'::jsonb, '{"location_text":{"ja":"Terminal 2","en":"Terminal 2"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Narita', 'nursery', '{"ja":"Nursery","en":"Nursery"}'::jsonb, '{"location_text":{"ja":"Terminal 1","en":"Terminal 1"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Narita', 'nursery', '{"ja":"Nursery","en":"Nursery"}'::jsonb, '{"location_text":{"ja":"Terminal 2","en":"Terminal 2"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Narita', 'nursery', '{"ja":"Nursery","en":"Nursery"}'::jsonb, '{"location_text":{"ja":"Terminal 3","en":"Terminal 3"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Narita', 'charging_station', '{"ja":"Charging_station","en":"Charging_station"}'::jsonb, '{"location_text":{"ja":"Terminal 1, Terminal 2, Terminal 3","en":"Terminal 1, Terminal 2, Terminal 3"},"is_available":true}'::jsonb);
INSERT INTO l3_facilities (station_id, type, name_i18n, attributes) VALUES ('odpt:Station:Airport.Narita', 'charging_station', '{"ja":"Charging_station","en":"Charging_station"}'::jsonb, '{"location_text":{"ja":"Terminal 1, Terminal 2, Terminal 3","en":"Terminal 1, Terminal 2, Terminal 3"},"is_available":true}'::jsonb);
