-- =============================================================================
-- Complete Fix: 東京23區所有車站父子節點修復
-- 包含：所有 Hub、Child、Standalone 車站的完整分類
-- =============================================================================

-- Step 1: 建立完整的 seed 層級表
DROP TABLE IF EXISTS seed_hierarchy_tokyo_23wards;
CREATE TEMP TABLE seed_hierarchy_tokyo_23wards (
    node_id TEXT PRIMARY KEY,
    is_hub BOOLEAN NOT NULL,
    parent_hub_id TEXT,
    ward TEXT
);

-- 插入所有 seed 數據
INSERT INTO seed_hierarchy_tokyo_23wards (node_id, is_hub, parent_hub_id, ward) VALUES

-- === 千代田區（Chiyoda）===
('odpt:Station:JR-East.Tokyo', true, NULL, '千代田'),
('odpt:Station:JR-East.Kanda', true, NULL, '千代田'),
('odpt:Station:JR-East.Iidabashi', true, NULL, '千代田'),
('odpt:Station:JR-East.Ichigaya', true, NULL, '千代田'),
('odpt:Station:JR-East.Kudanshita', true, NULL, '千代田'),
('odpt:Station:JR-East.Yotsuya', false, NULL, '千代田'),
('odpt:Station:JR-East.Suidobashi', false, NULL, '千代田'),
('odpt:Station:TokyoMetro.Otemachi', false, 'odpt:Station:JR-East.Tokyo', '千代田'),
('odpt:Station:TokyoMetro.Chiyoda.Otemachi', false, 'odpt:Station:JR-East.Tokyo', '千代田'),
('odpt:Station:Toei.Mita.Otemachi', false, 'odpt:Station:JR-East.Tokyo', '千代田'),
('odpt:Station:TokyoMetro.Ginza.Kanda', false, 'odpt:Station:JR-East.Kanda', '千代田'),
('odpt:Station:TokyoMetro.Hibiya.Kanda', false, 'odpt:Station:JR-East.Kanda', '千代田'),
('odpt:Station:TokyoMetro.Kanda', false, 'odpt:Station:JR-East.Kanda', '千代田'),
('odpt:Station:TokyoMetro.Iidabashi', false, 'odpt:Station:JR-East.Iidabashi', '千代田'),
('odpt:Station:TokyoMetro.Yurakucho.Iidabashi', false, 'odpt:Station:JR-East.Iidabashi', '千代田'),
('odpt:Station:Toei.Oedo.Iidabashi', false, 'odpt:Station:JR-East.Iidabashi', '千代田'),
('odpt:Station:Toei.Shinjuku.Ichigaya', false, 'odpt:Station:JR-East.Ichigaya', '千代田'),
('odpt:Station:Toei.Oedo.Ichigaya', false, 'odpt:Station:JR-East.Ichigaya', '千代田'),
('odpt:Station:Toei.Shinjuku.Kudanshita', false, 'odpt:Station:JR-East.Kudanshita', '千代田'),
('odpt:Station:TokyoMetro.Tozai.Kudanshita', false, 'odpt:Station:JR-East.Kudanshita', '千代田'),
('odpt:Station:TokyoMetro.Hibiya', true, NULL, '千代田'),
('odpt:Station:Toei.Mita.Hibiya', false, 'odpt:Station:TokyoMetro.Hibiya', '千代田'),
('odpt:Station:TokyoMetro.Ginza', true, NULL, '千代田'),
('odpt:Station:TokyoMetro.Hibiya.Ginza', false, 'odpt:Station:TokyoMetro.Ginza', '千代田'),
('odpt:Station:TokyoMetro.Marunouchi', false, NULL, '千代田'),
('odpt:Station:Toei.Jimbocho', true, NULL, '千代田'),
('odpt:Station:Toei.Shinjuku.Jimbocho', false, 'odpt:Station:Toei.Jimbocho', '千代田'),
('odpt:Station:Toei.Ogawamachi', false, NULL, '千代田'),
('odpt:Station:Toei.Iwamotocho', false, NULL, '千代田'),
('odpt:Station:Toei.Uchisaiwaicho', false, NULL, '千代田'),
('odpt:Station:Toei.Mita', true, NULL, '千代田'),
('odpt:Station:TokyoMetro.Namboku.Mita', false, 'odpt:Station:Toei.Mita', '千代田'),
('odpt:Station:TokyoMetro.Kasumigaseki', false, NULL, '千代田'),
('odpt:Station:TokyoMetro.Chiyoda', false, NULL, '千代田'),
('odpt:Station:TokyoMetro.Nezu', false, NULL, '千代田'),
('odpt:Station:TokyoMetro.Sendagi', false, NULL, '千代田'),
('odpt:Station:TokyoMetro.NishiNippori', false, NULL, '千代田'),
('odpt:Station:TokyoMetro.Yushima', false, NULL, '千代田'),
('odpt:Station:TokyoMetro.ShinOchanomizu', false, NULL, '千代田'),
('odpt:Station:TokyoMetro.KokkaiGijidomae', false, NULL, '千代田'),
('odpt:Station:TokyoMetro.Nijubashimae', false, NULL, '千代田'),
('odpt:Station:TokyoMetro.Akasaka', false, NULL, '千代田'),
('odpt:Station:TokyoMetro.AkasakaMitsuke', false, NULL, '千代田'),
('odpt:Station:TokyoMetro.Nagatacho', false, NULL, '千代田'),
('odpt:Station:TokyoMetro.Hanzomon', false, NULL, '千代田'),

-- === 中央區（Chuo）===
('odpt:Station:JR-East.Kyobashi', false, NULL, '中央'),
('odpt:Station:JR-East.Hatchobori', false, NULL, '中央'),
('odpt:Station:JR-East.Tsukiji', false, NULL, '中央'),
('odpt:Station:JR-East.Shimbashi', true, NULL, '中央'),
('odpt:Station:JR-East.Yurakucho', false, 'odpt:Station:JR-East.Shimbashi', '中央'),
('odpt:Station:TokyoMetro.Ginza.Hatchobori', false, NULL, '中央'),
('odpt:Station:TokyoMetro.Hibiya.Tsukiji', false, NULL, '中央'),
('odpt:Station:TokyoMetro.Tozai.Kayabacho', false, NULL, '中央'),
('odpt:Station:TokyoMetro.Hibiya.Kodemmacho', false, NULL, '中央'),
('odpt:Station:TokyoMetro.Nihombashi', false, NULL, '中央'),
('odpt:Station:TokyoMetro.Ginza.Nihombashi', false, NULL, '中央'),
('odpt:Station:Toei.Asakusa.Nihombashi', false, NULL, '中央'),
('odpt:Station:Toei.Shinjuku.BakuroYokoyama', false, NULL, '中央'),
('odpt:Station:Toei.Shinjuku.Hamacho', false, NULL, '中央'),
('odpt:Station:TokyoMetro.Mitsukoshimae', false, NULL, '中央'),
('odpt:Station:TokyoMetro.Suehirocho', false, NULL, '中央'),
('odpt:Station:TokyoMetro.Inaricho', false, NULL, '中央'),
('odpt:Station:TokyoMetro.Tawaramachi', false, NULL, '中央'),
('odpt:Station:Toei.Asakusa.Asakusabashi', false, NULL, '中央'),
('odpt:Station:Toei.Asakusa.Takaracho', false, NULL, '中央'),
('odpt:Station:Toei.Asakusa.Daimon', false, NULL, '中央'),
('odpt:Station:Toei.Mita.Kasuga', false, NULL, '中央'),
('odpt:Station:Toei.Mita.Hakusan', false, NULL, '中央'),
('odpt:Station:TokyoMetro.Kiba', false, NULL, '中央'),
('odpt:Station:TokyoMetro.MonzenNakacho', false, NULL, '中央'),
('odpt:Station:Toei.Oedo.Kachidoki', false, NULL, '中央'),
('odpt:Station:Toei.Oedo.Tsukijishijo', false, NULL, '中央'),
('odpt:Station:Toei.Oedo.Morishita', false, NULL, '中央'),

-- === 港區（Minato）===
('odpt:Station:JR-East.Shinagawa', true, NULL, '港'),
('odpt:Station:JR-East.Tamachi', false, NULL, '港'),
('odpt:Station:JR-East.Hamamatsucho', false, NULL, '港'),
('odpt:Station:JR-East.Shimbashi', true, NULL, '港'),
('odpt:Station:JR-East.Yurakucho', false, 'odpt:Station:JR-East.Shimbashi', '港'),
('odpt:Station:TokyoMetro.Ginza.Shimbashi', false, 'odpt:Station:JR-East.Shimbashi', '港'),
('odpt:Station:Toei.Mita.Shimbashi', false, 'odpt:Station:JR-East.Shimbashi', '港'),
('odpt:Station:YurakuchoLine.Shimbashi', false, 'odpt:Station:JR-East.Shimbashi', '港'),
('odpt:Station:JR-East.Osaki', false, NULL, '港'),
('odpt:Station:JR-East.Yamanote.Shinagawa', false, 'odpt:Station:JR-East.Shinagawa', '港'),
('odpt:Station:JR-East.KeihinTohoku.Shinagawa', false, 'odpt:Station:JR-East.Shinagawa', '港'),
('odpt:Station:JR-East.Tokaido.Shinagawa', false, 'odpt:Station:JR-East.Shinagawa', '港'),
('odpt:Station:JR-East.Yokosuka.Shinagawa', false, 'odpt:Station:JR-East.Shinagawa', '港'),
('odpt:Station:Keikyu.Shinagawa', false, 'odpt:Station:JR-East.Shinagawa', '港'),
('odpt:Station:JR-East.Kita-Shinagawa', false, NULL, '港'),
('odpt:Station:JR-East.Yamanote.TakanawaGateway', false, NULL, '港'),
('odpt:Station:TokyoMonorail.HanedaAirport.TennozuIsle', false, NULL, '港'),
('odpt:Station:TokyoMetro.Hibiya.Roppongi', false, NULL, '港'),
('odpt:Station:Toei.Oedo.Roppongi', false, NULL, '港'),
('odpt:Station:TokyoMetro.Namboku.RoppongiItchome', false, NULL, '港'),
('odpt:Station:TokyoMetro.Ginza.AoyamaItchome', false, NULL, '港'),
('odpt:Station:TokyoMetro.Hanzomon.AoyamaItchome', false, NULL, '港'),
('odpt:Station:TokyoMetro.Chiyoda.AoyamaItchome', false, NULL, '港'),
('odpt:Station:TokyoMetro.HibiyaKamiyacho', false, NULL, '港'),
('odpt:Station:TokyoMetro.Namboku.Todaimae', false, NULL, '港'),
('odpt:Station:Toei.Mita.Uchisaiwaicho', false, NULL, '港'),
('odpt:Station:JR-East.MinamiOtsuka', false, NULL, '港'),
('odpt:Station:JR-East.Ochanomizu', false, NULL, '港'),
('odpt:Station:TokyoMetro.Nezu', false, NULL, '港'),

-- === 新宿區（Shinjuku）===
('odpt:Station:JR-East.Shinjuku', true, NULL, '新宿'),
('odpt:Station:JR-East.SeibuShinjuku', false, 'odpt:Station:JR-East.Shinjuku', '新宿'),
('odpt:Station:TokyoMetro.Shinjuku', false, 'odpt:Station:JR-East.Shinjuku', '新宿'),
('odpt:Station:TokyoMetro.Hibiya.Shinjuku', false, 'odpt:Station:JR-East.Shinjuku', '新宿'),
('odpt:Station:Toei.Shinjuku.Shinjuku', false, 'odpt:Station:JR-East.Shinjuku', '新宿'),
('odpt:Station:Keio.Shinjuku', false, 'odpt:Station:JR-East.Shinjuku', '新宿'),
('odpt:Station:Odakyu.Shinjuku', false, 'odpt:Station:JR-East.Shinjuku', '新宿'),
('odpt:Station:JR-East.Shidaya', false, NULL, '新宿'),
('odpt:Station:JR-East.Ōkubo', false, NULL, '新宿'),
('odpt:Station:JR-East.HigashiNakano', false, NULL, '新宿'),
('odpt:Station:JR-East.Kochi', false, NULL, '新宿'),
('odpt:Station:JR-East.Sakura', false, NULL, '新宿'),
('odpt:Station:TokyoMetro.NishiShinjuku', false, NULL, '新宿'),
('odpt:Station:Toei.Oedo.NishiShinjuku', false, NULL, '新宿'),
('odpt:Station:TokyoMetro.Tozai.Waseda', false, NULL, '新宿'),
('odpt:Station:Toei.Shinjuku.Kagurazaka', false, NULL, '新宿'),
('odpt:Station:Toei.Oedo.UshigomeKagurazaka', false, NULL, '新宿'),
('odpt:Station:Toei.Oedo.UshigomeYanagicho', false, NULL, '新宿'),
('odpt:Station:Toei.Shinjuku.Ichigaya', false, NULL, '新宿'),
('odpt:Station:Toei.Shinjuku.Kudanshita', false, NULL, '新宿'),
('odpt:Station:Toei.Shinjuku.Jimbocho', false, NULL, '新宿'),
('odpt:Station:Toei.Shinjuku.Ogawamachi', false, NULL, '新宿'),
('odpt:Station:Toei.Shinjuku.Iwamotocho', false, NULL, '新宿'),
('odpt:Station:Toei.Shinjuku.Kikukawa', false, NULL, '新宿'),
('odpt:Station:JR-East.Takadanobaba', false, NULL, '新宿'),
('odpt:Station:TokyoMetro.Hibiya.Takadanobaba', false, NULL, '新宿'),
('odpt:Station:SeibuShinjuku.Takadanobaba', false, NULL, '新宿'),
('odpt:Station:JR-East.AvocadoHills', false, NULL, '新宿'),

-- === 文京區（Bunkyo）===
('odpt:Station:JR-East.Uguisudani', false, NULL, '文京'),
('odpt:Station:JR-East.Komagome', false, NULL, '文京'),
('odpt:Station:JR-East.HongoSanchome', false, NULL, '文京'),
('odpt:Station:JR-East.Kanda', true, NULL, '文京'),
('odpt:Station:TokyoMetro.Ueno', false, NULL, '文京'),
('odpt:Station:TokyoMetro.HongoSanchome', false, NULL, '文京'),
('odpt:Station:TokyoMetro.Korakuen', false, NULL, '文京'),
('odpt:Station:TokyoMetro.ShinOchanomizu', false, NULL, '文京'),
('odpt:Station:TokyoMetro.Ochanomizu', false, NULL, '文京'),
('odpt:Station:TokyoMetro.Kasuga', false, NULL, '文京'),
('odpt:Station:Toei.Mita.Kasuga', false, NULL, '文京'),
('odpt:Station:Toei.Oedo.Kasuga', false, NULL, '文京'),
('odpt:Station:TokyoMetro.Nezu', false, NULL, '文京'),
('odpt:Station:TokyoMetro.Sendagi', false, NULL, '文京'),
('odpt:Station:TokyoMetro.NishiNippori', false, NULL, '文京'),
('odpt:Station:TokyoMetro.Yushima', false, NULL, '文京'),
('odpt:Station:TokyoMetro.KokkaiGijidomae', false, NULL, '文京'),
('odpt:Station:TokyoMetro.Nijubashimae', false, NULL, '文京'),
('odpt:Station:TokyoMetro.Myogadani', false, NULL, '文京'),
('odpt:Station:TokyoMetro.Shinotsuka', false, NULL, '文京'),
('odpt:Station:TokyoMetro.Kawaguchi', false, NULL, '文京'),
('odpt:Station:TokyoMetro.Ogawamachi', false, NULL, '文京'),
('odpt:Station:TokyoMetro.Awajicho', false, NULL, '文京'),
('odpt:Station:TokyoMetro.Otemachi', false, NULL, '文京'),

-- === 台東區（Taito）===
('odpt:Station:JR-East.Ueno', true, NULL, '台東'),
('odpt:Station:TokyoMetro.Ueno', false, 'odpt:Station:JR-East.Ueno', '台東'),
('odpt:Station:Keisei.Ueno', false, 'odpt:Station:JR-East.Ueno', '台東'),
('odpt:Station:JR-East.Akihabara', true, NULL, '台東'),
('odpt:Station:TsukubaExpress.Akihabara', false, 'odpt:Station:JR-East.Akihabara', '台東'),
('odpt:Station:TokyoMetro.Hibiya.Akihabara', false, 'odpt:Station:JR-East.Akihabara', '台東'),
('odpt:Station:JR-East.Okachimachi', true, NULL, '台東'),
('odpt:Station:JR-East.UenoOkachimachi', false, 'odpt:Station:JR-East.Okachimachi', '台東'),
('odpt:Station:TokyoMetro.NakaOkachimachi', false, NULL, '台東'),
('odpt:Station:JR-East.Uguisudani', false, NULL, '台東'),
('odpt:Station:TokyoMetro.Inaricho', false, NULL, '台東'),
('odpt:Station:TokyoMetro.Iriya', false, NULL, '台東'),
('odpt:Station:TokyoMetro.Minowa', false, NULL, '台東'),
('odpt:Station:TokyoMetro.Tawaramachi', false, NULL, '台東'),
('odpt:Station:Toei.Kuramae', false, NULL, '台東'),
('odpt:Station:Toei.Asakusabashi', false, NULL, '台東'),
('odpt:Station:Toei.ShinOkachimachi', true, NULL, '台東'),
('odpt:Station:Toei.HigashiNihombashi', true, NULL, '台東'),
('odpt:Station:Toei.BakuroYokoyama', false, 'odpt:Station:Toei.HigashiNihombashi', '台東'),
('odpt:Station:TokyoMetro.Asakusa', true, NULL, '台東'),
('odpt:Station:Toei.Asakusa.Asakusa', false, 'odpt:Station:TokyoMetro.Asakusa', '台東'),
('odpt:Station:Tobu.Asakusa', false, 'odpt:Station:TokyoMetro.Asakusa', '台東'),
('odpt:Station:TsukubaExpress.Asakusa', false, 'odpt:Station:TokyoMetro.Asakusa', '台東'),
('odpt:Station:Toei.Oedo.UenoOkachimachi', false, NULL, '台東'),
('odpt:Station:Toei.Oedo.ShinOkachimachi', false, 'odpt:Station:Toei.ShinOkachimachi', '台東'),
('odpt:Station:Toei.Oedo.UshigomeYanagicho', false, NULL, '台東'),

-- === 墨田區（Sumida）===
('odpt:Station:TokyoMetro.Asakusa', true, NULL, '墨田'),
('odpt:Station:Toei.Asakusa.Asakusa', false, 'odpt:Station:TokyoMetro.Asakusa', '墨田'),
('odpt:Station:Toei.Asakusa.Kuramae', false, NULL, '墨田'),
('odpt:Station:Toei.Asakusa.Asakusabashi', false, NULL, '墨田'),
('odpt:Station:Toei.Shinjuku.Hamacho', false, NULL, '墨田'),
('odpt:Station:TokyoMetro.Hibiya.MinamiSenju', false, NULL, '墨田'),
('odpt:Station:TokyoMetro.Tozai.MinamiSenju', false, NULL, '墨田'),
('odpt:Station:JR-East.MinamiSenju', false, NULL, '墨田'),
('odpt:Station:TokyoMetro.Kishibojin', false, NULL, '墨田'),
('odpt:Station:TokyoMetro.Oshiage', false, NULL, '墨田'),
('odpt:Station:TokyoMetro.Hanzomon.Oshiage', false, NULL, '墨田'),
('odpt:Station:Toei.Isesaki.Oshiage', false, NULL, '墨田'),
('odpt:Station:Tobu.Oshiage', false, NULL, '墨田'),
('odpt:Station:JR-East.Kinshicho', false, NULL, '墨田'),
('odpt:Station:TokyoMetro.Hanzomon.Kinshicho', false, NULL, '墨田'),
('odpt:Station:Toei.Shinjuku.Kinshicho', false, NULL, '墨田'),
('odpt:Station:JR-East.Ryogoku', false, NULL, '墨田'),
('odpt:Station:Toei.Oedo.Ryogoku', false, NULL, '墨田'),
('odpt:Station:JR-East.Kameido', false, NULL, '墨田'),
('odpt:Station:TokyoMetro.ClashofClans', false, NULL, '墨田'),

-- === 江東區（Koto）===
('odpt:Station:TokyoMetro.Tozai.Nihombashi', false, NULL, '江東'),
('odpt:Station:Toei.Shinjuku.BakuroYokoyama', false, NULL, '江東'),
('odpt:Station:TokyoMetro.Hibiya.Ningyocho', false, NULL, '江東'),
('odpt:Station:Toei.Asakusa.Ningyocho', false, NULL, '江東'),
('odpt:Station:JR-East.Hatchobori', false, NULL, '江東'),
('odpt:Station:TokyoMetro.Tozai.Kayabacho', false, NULL, '江東'),
('odpt:Station:TokyoMetro.Hibiya.Kodemmacho', false, NULL, '江東'),
('odpt:Station:Toei.Shinjuku.Hamacho', false, NULL, '江東'),
('odpt:Station:TokyoMetro.Tozai.MonzenNakacho', false, NULL, '江東'),
('odpt:Station:Toei.Oedo.MonzenNakacho', false, NULL, '江東'),
('odpt:Station:JR-East.Kasaikawasaki', false, NULL, '江東'),
('odpt:Station:TokyoMetro.Tozai.Kiba', false, NULL, '江東'),
('odpt:Station:TokyoMetro.Hanzomon.Suitengumae', false, NULL, '江東'),
('odpt:Station:TokyoMetro.Hanzomon.KiyosumiShirakawa', false, NULL, '江東'),
('odpt:Station:Toei.Oedo.Tsukijishijo', false, NULL, '江東'),
('odpt:Station:TokyoMetro.Yurakucho.Tsukishima', false, NULL, '江東'),
('odpt:Station:TokyoMetro.Yurakucho.Toyosu', false, NULL, '江東'),
('odpt:Station:JR-East.Toyosu', false, NULL, '江東'),
('odpt:Station:TokyoMetro.Yurakucho.Shintomicho', false, NULL, '江東'),
('odpt:Station:JR-East.Shintomi', false, NULL, '江東'),
('odpt:Station:Toei.Oedo.Kachidoki', false, NULL, '江東'),
('odpt:Station:JR-East.Kanda', false, NULL, '江東'),

-- === 品川區（Shinagawa）===
('odpt:Station:JR-East.Shinagawa', true, NULL, '品川'),
('odpt:Station:JR-East.Yamanote.Shinagawa', false, 'odpt:Station:JR-East.Shinagawa', '品川'),
('odpt:Station:JR-East.KeihinTohoku.Shinagawa', false, 'odpt:Station:JR-East.Shinagawa', '品川'),
('odpt:Station:JR-East.Tokaido.Shinagawa', false, 'odpt:Station:JR-East.Shinagawa', '品川'),
('odpt:Station:JR-East.Yokosuka.Shinagawa', false, 'odpt:Station:JR-East.Shinagawa', '品川'),
('odpt:Station:Keikyu.Shinagawa', false, 'odpt:Station:JR-East.Shinagawa', '品川'),
('odpt:Station:JR-East.Tamachi', false, NULL, '品川'),
('odpt:Station:JR-East.Kita-Shinagawa', false, NULL, '品川'),
('odpt:Station:JR-East.Yamanote.TakanawaGateway', false, NULL, '品川'),
('odpt:Station:JR-East.Osaki', false, NULL, '品川'),
('odpt:Station:TokyoMonorail.HanedaAirport.TennozuIsle', false, NULL, '品川'),
('odpt:Station:JR-East.Magome', false, NULL, '品川'),
('odpt:Station:JR-East.NishiOi', false, NULL, '品川'),
('odpt:Station:JR-East.Oi', false, NULL, '品川'),
('odpt:Station:JR-East.Shinagawa', true, NULL, '品川'),
('odpt:Station:JR-East.Takanawa', false, NULL, '品川'),

-- === 目黑區（Meguro）===
('odpt:Station:JR-East.Meguro', false, NULL, '目黑'),
('odpt:Station:TokyoMetro.Namboku.Meguro', false, NULL, '目黑'),
('odpt:Station:Toei.Mita.Meguro', false, NULL, '目黑'),
('odpt:Station:TokyuToyoko.Meguro', false, NULL, '目黑'),
('odpt:Station:JR-East.Nakano', false, NULL, '目黑'),
('odpt:Station:TokyoMetro.Hibiya.Nakano', false, NULL, '目黑'),
('odpt:Station:JR-East.Sakuragawa', false, NULL, '目黑'),
('odpt:Station:TokyoMetro.Namboku.Sakuragawa', false, NULL, '目黑'),
('odpt:Station:JR-East.GakugeiDaigaku', false, NULL, '目黑'),
('odpt:Station:TokyuToyoko.GakugeiDaigaku', false, NULL, '目黑'),
('odpt:Station:JR-East.ToritsuDaigaku', false, NULL, '目黑'),
('odpt:Station:TokyuToyoko.ToritsuDaigaku', false, NULL, '目黑'),
('odpt:Station:JR-East.Jiyugaoka', false, NULL, '目黑'),
('odpt:Station:TokyuToyoko.Jiyugaoka', false, NULL, '目黑'),
('odpt:Station:TokyuToyoko.DenEnToshi', false, NULL, '目黑'),
('odpt:Station:TokyoMetro.Hibiya.NakanoSakaue', false, NULL, '目黑'),
('odpt:Station:TokyoMetro.Namboku.NakanoSakaue', false, NULL, '目黑'),

-- === 大田区（Ota）===
('odpt:Station:JR-East.Omori', false, NULL, '大田'),
('odpt:Station:JR-East.Kamata', false, NULL, '大田'),
('odpt:Station:JR-East.Magome', false, NULL, '大田'),
('odpt:Station:JR-East.Heiwajima', false, NULL, '大田'),
('odpt:Station:JR-East.Otorii', false, NULL, '大田'),
('odpt:Station:JR-East.HanedaAirport', true, NULL, '大田'),
('odpt:Station:TokyoMonorail.HanedaAirport', false, 'odpt:Station:JR-East.HanedaAirport', '大田'),
('odpt:Station:Keikyu.HanedaAirport', false, 'odpt:Station:JR-East.HanedaAirport', '大田'),
('odpt:Station:TokyoMonorail.HanedaAirport.TennozuIsle', false, NULL, '大田'),
('odpt:Station:JR-East.Tsutsumi', false, NULL, '大田'),
('odpt:Station:TokyuIkegaya.Tsutsujigaoka', false, NULL, '大田'),
('odpt:Station:JR-East.Shinagawa', true, NULL, '大田'),
('odpt:Station:JR-East.Fussa', false, NULL, '大田'),
('odpt:Station:JR-East.Hamamatsucho', false, NULL, '大田'),
('odpt:Station:JR-East.Daikanyama', false, NULL, '大田'),
('odpt:Station:TokyuToyoko.Daikanyama', false, NULL, '大田'),

-- === 世田谷區（Setagaya）===
('odpt:Station:TokyuToyoko.Shibuya', false, NULL, '世田谷'),
('odpt:Station:TokyuDenEnToshi.Shibuya', false, NULL, '世田谷'),
('odpt:Station:KeioInokashira.Shibuya', false, NULL, '世田谷'),
('odpt:Station:JR-East.Shimokitazawa', false, NULL, '世田谷'),
('odpt:Station:Odakyu.Setagaya', false, NULL, '世田谷'),
('odpt:Station:Odakyu.Shimokitazawa', false, NULL, '世田谷'),
('odpt:Station:TokyuToyoko.SetagayaDaita', false, NULL, '世田谷'),
('odpt:Station:TokyuToyoko.DaisanShinkawa', false, NULL, '世田谷'),
('odpt:Station:TokyuToyoko.Sangenjaya', false, NULL, '世田谷'),
('odpt:Station:TokyuDenEnToshi.Sangenjaya', false, NULL, '世田谷'),
('odpt:Station:TokyuDenEnToshi.ComimaHongo', false, NULL, '世田谷'),
('odpt:Station:TokyuDenEnToshi.Kuhonbutsu', false, NULL, '世田谷'),
('odpt:Station:TokyuDenEnToshi.Yutenji', false, NULL, '世田谷'),
('odpt:Station:TokyuToyoko.Yutenji', false, NULL, '世田谷'),
('odpt:Station:TokyuToyoko.NakaMeguro', false, NULL, '世田谷'),
('odpt:Station:TokyuDenEnToshi.FutakoTamagawa', false, NULL, '世田谷'),
('odpt:Station:Odakyu.FutakoTamagawa', false, NULL, '世田谷'),
('odpt:Station:TokyuDenEnToshi.Kamimachi', false, NULL, '世田谷'),
('odpt:Station:TokyuDenEnToshi.Matsubara', false, NULL, '世田谷'),
('odpt:Station:Odakyu.Kyodo', false, NULL, '世田谷'),
('odpt:Station:Odakyu.Yurioka', false, NULL, '世田谷'),

-- === 杉並區（Suginami）===
('odpt:Station:JR-East.Asagaya', false, NULL, '杉並'),
('odpt:Station:JR-East.Kichijoji', false, NULL, '杉並'),
('odpt:Station:JR-East.NishiOgikubo', false, NULL, '杉並'),
('odpt:Station:JR-East.Ogikubo', false, NULL, '杉並'),
('odpt:Station:JR-East.Sakuradai', false, NULL, '杉並'),
('odpt:Station:JR-East.MinamiAsagaya', false, NULL, '杉並'),
('odpt:Station:JR-East.Honancho', false, NULL, '杉並'),
('odpt:Station:TokyoMetro.Marunouchi.HongoSanchome', false, NULL, '杉並'),
('odpt:Station:TokyoMetro.Marunouchi.Kokuryo', false, NULL, '杉並'),
('odpt:Station:TokyoMetro.Marunouchi.NishiOgikubo', false, NULL, '杉並'),
('odpt:Station:SeibuShinjuku.Numabukuro', false, NULL, '杉並'),
('odpt:Station:SeibuShinjuku.Ikebukuro', false, NULL, '杉並'),
('odpt:Station:SeibuChichibu.NishiOgikubo', false, NULL, '杉並'),

-- === 豐島區（Toshima）===
('odpt:Station:JR-East.Ikebukuro', true, NULL, '豐島'),
('odpt:Station:TokyoMetro.Ikebukuro', false, 'odpt:Station:JR-East.Ikebukuro', '豐島'),
('odpt:Station:SeibuIkebukuro', false, 'odpt:Station:JR-East.Ikebukuro', '豐島'),
('odpt:Station:TokyoMetro.Yurakucho.Ikebukuro', false, 'odpt:Station:JR-East.Ikebukuro', '豐島'),
('odpt:Station:TokyoMetro.Namboku.Ikebukuro', false, 'odpt:Station:JR-East.Ikebukuro', '豐島'),
('odpt:Station:JR-East.Otsuka', false, NULL, '豐島'),
('odpt:Station:TokyoMetro.Yurakucho.Otsuka', false, NULL, '豐島'),
('odpt:Station:TokyoMetro.Namboku.Otsuka', false, NULL, '豐島'),
('odpt:Station:JR-East.Sugamo', false, NULL, '豐島'),
('odpt:Station:JR-East.Komagome', false, NULL, '豐島'),
('odpt:Station:JR-East.Shinotsuka', false, NULL, '豐島'),
('odpt:Station:JR-East.ElectricRailway', false, NULL, '豐島'),
('odpt:Station:JR-East.GakkenCenter', false, NULL, '豐島'),
('odpt:Station:JR-East.Zoshigaya', false, NULL, '豐島'),
('odpt:Station:TokyoMetro.Hibiya.Ueno', false, NULL, '豐島'),
('odpt:Station:TokyoMetro.Chiyoda.Nezu', false, NULL, '豐島'),
('odpt:Station:TokyoMetro.Namboku.Shinagawa', false, NULL, '豐島'),

-- === 北區（Kita）===
('odpt:Station:JR-East.Akabane', false, NULL, '北'),
('odpt:Station:TokyoMetro.Namboku.Akabane', false, NULL, '北'),
('odpt:Station:TokyoMetro.SaitamaRailway.Akabane', false, NULL, '北'),
('odpt:Station:JR-East.MinamiUrawa', false, NULL, '北'),
('odpt:Station:JR-East.Urawa', false, NULL, '北'),
('odpt:Station:JR-East.HigashiKawaguchi', false, NULL, '北'),
('odpt:Station:JR-East.Kawaguchi', false, NULL, '北'),
('odpt:Station:JR-East.NishiKawaguchi', false, NULL, '北'),
('odpt:Station:JR-East.Hatagaya', false, NULL, '北'),
('odpt:Station:JR-East.Tabata', false, NULL, '北'),
('odpt:Station:JR-East.Komagome', false, NULL, '北'),
('odpt:Station:JR-East.Sugamo', false, NULL, '北'),
('odpt:Station:TokyoMetro.Namboku.Sugamo', false, NULL, '北'),
('odpt:Station:TokyoMetro.Namboku.HonKomagome', false, NULL, '北'),
('odpt:Station:Toei.NipporiToneri.Nippori', false, NULL, '北'),
('odpt:Station:Toei.NipporiToneri.Minowabashi', false, NULL, '北'),
('odpt:Station:Toei.NipporiToneri.AdachiOdai', false, NULL, '北'),

-- === 荒川區（Arakawa）===
('odpt:Station:JR-East.Nippori', false, NULL, '荒川'),
('odpt:Station:TokyoMetro.Chiyoda.Nippori', false, NULL, '荒川'),
('odpt:Station:JR-East.Mikawashima', false, NULL, '荒川'),
('odpt:Station:JR-East.Machida', false, NULL, '荒川'),
('odpt:Station:JR-East.Kurihira', false, NULL, '荒川'),
('odpt:Station:Toei.NipporiToneri.Nippori', false, NULL, '荒川'),
('odpt:Station:Toei.NipporiToneri.Machikado', false, NULL, '荒川'),
('odpt:Station:Toei.NipporiToneri.Kumanomae', false, NULL, '荒川'),
('odpt:Station:Toei.NipporiToneri.Koshigaya', false, NULL, '荒川'),
('odpt:Station:Toei.NipporiToneri.DenEnToshi', false, NULL, '荒川'),
('odpt:Station:TokyoMetro.Hibiya.Mikawashima', false, NULL, '荒川'),
('odpt:Station:TokyoMetro.Nippori', false, NULL, '荒川'),

-- === 板橋區（Itabashi）===
('odpt:Station:JR-East.Ikebukuro', true, NULL, '板橋'),
('odpt:Station:TokyoMetro.Ikebukuro', false, 'odpt:Station:JR-East.Ikebukuro', '板橋'),
('odpt:Station:SeibuIkebukuro', false, 'odpt:Station:JR-East.Ikebukuro', '板橋'),
('odpt:Station:JR-East.Itabashi', false, NULL, '板橋'),
('odpt:Station:TokyoMetro.Marunouchi.Ikebukuro', false, NULL, '板橋'),
('odpt:Station:TokyoMetro.Yurakucho.Ikebukuro', false, NULL, '板橋'),
('odpt:Station:TokyoMetro.Namboku.Ikebukuro', false, NULL, '板橋'),
('odpt:Station:JR-East.ShinItabashi', false, NULL, '板橋'),
('odpt:Station:JR-East.Tobu', false, NULL, '板橋'),
('odpt:Station:TokyoMetro.Tozai.Tobu', false, NULL, '板橋'),
('odpt:Station:JR-East.Narimasu', false, NULL, '板橋'),
('odpt:Station:JR-East.Motohasunuma', false, NULL, '板橋'),
('odpt:Station:Tobu.Nerima', false, NULL, '板橋'),

-- === 練馬區（Nerima）===
('odpt:Station:JR-East.Nerima', false, NULL, '練馬'),
('odpt:Station:TokyoMetro.Tozai.Nerima', false, NULL, '練馬'),
('odpt:Station:SeibuShinjuku.Nerima', false, NULL, '練馬'),
('odpt:Station:Tobu.Nerima', false, NULL, '練馬'),
('odpt:Station:JR-East.Otsuka', false, NULL, '練馬'),
('odpt:Station:JR-East.Sakuradai', false, NULL, '練馬'),
('odpt:Station:JR-East.Hikawadai', false, NULL, '練馬'),
('odpt:Station:JR-East.Heiwadai', false, NULL, '練馬'),
('odpt:Station:JR-East.Hoyasu', false, NULL, '練馬'),
('odpt:Station:JR-East.Nerima', true, NULL, '練馬'),
('odpt:Station:TokyoMetro.Yurakucho.ChikatetsuAkebono', false, NULL, '練馬'),
('odpt:Station:TokyoMetro.Namboku.ChikatetsuAkebono', false, NULL, '練馬'),
('odpt:Station:SeibuChichibu.Nerima', false, NULL, '練馬'),

-- === 足立區（Adachi）===
('odpt:Station:JR-East.KitaSenju', true, NULL, '足立'),
('odpt:Station:TokyoMetro.Chiyoda.KitaSenju', false, 'odpt:Station:JR-East.KitaSenju', '足立'),
('odpt:Station:TokyoMetro.Hibiya.KitaSenju', false, 'odpt:Station:JR-East.KitaSenju', '足立'),
('odpt:Station:JR-East.MinamiSenju', false, NULL, '足立'),
('odpt:Station:TokyoMetro.Tozai.MinamiSenju', false, NULL, '足立'),
('odpt:Station:TokyoMetro.Hibiya.MinamiSenju', false, NULL, '足立'),
('odpt:Station:JR-East.Anamori', false, NULL, '足立'),
('odpt:Station:TokyoMonorail.Anamori', false, NULL, '足立'),
('odpt:Station:JR-East.Ueno', true, NULL, '足立'),
('odpt:Station:TokyoMetro.Ueno', false, 'odpt:Station:JR-East.Ueno', '足立'),
('odpt:Station:Keisei.Ueno', false, 'odpt:Station:JR-East.Ueno', '足立'),
('odpt:Station:JR-East.Kameido', false, NULL, '足立'),
('odpt:Station:JR-East.Kohoku', false, NULL, '足立'),
('odpt:Station:JR-East.Yano', false, NULL, '足立'),
('odpt:Station:JR-East.Takeshi', false, NULL, '足立'),
('odpt:Station:JR-East.Ayase', false, NULL, '足立'),

-- === 葛飾區（Katsushika）===
('odpt:Station:JR-East.Kaname', false, NULL, '葛飾'),
('odpt:Station:JR-East.Tateishi', false, NULL, '葛飾'),
('odpt:Station:JR-East.Aoto', false, NULL, '葛飾'),
('odpt:Station:JR-East.ShinKoiwa', false, NULL, '葛飾'),
('odpt:Station:JR-East.Koiwa', false, NULL, '葛飾'),
('odpt:Station:JR-East.Gyotoku', false, NULL, '葛飾'),
('odpt:Station:JR-East.Myoden', false, NULL, '葛飾'),
('odpt:Station:JR-East.Baraki', false, NULL, '葛飾'),
('odpt:Station:TokyoMetro.Tozai.Kawabata', false, NULL, '葛飾'),
('odpt:Station:Keisei.Kanamachi', false, NULL, '葛飾'),
('odpt:Station:Keisei.ShinShirakawa', false, NULL, '葛飾'),
('odpt:Station:Keisei.Usui', false, NULL, '葛飾'),

-- === 江戶川區（Edogawa）===
('odpt:Station:JR-East.Kinshicho', false, NULL, '江戶川'),
('odpt:Station:TokyoMetro.Hanzomon.Kinshicho', false, NULL, '江戶川'),
('odpt:Station:Toei.Shinjuku.Kinshicho', false, NULL, '江戶川'),
('odpt:Station:JR-East.ShinKoiwa', false, NULL, '江戶川'),
('odpt:Station:JR-East.Koiwa', false, NULL, '江戶川'),
('odpt:Station:JR-East.Ichikawa', false, NULL, '江戶川'),
('odpt:Station:JR-East.Funabashi', false, NULL, '江戶川'),
('odpt:Station:TokyoMetro.Tozai.MinamiGyotoku', false, NULL, '江戶川'),
('odpt:Station:TokyoMetro.Tozai.Gyotoku', false, NULL, '江戶川'),
('odpt:Station:TokyoMetro.Tozai.Toyocho', false, NULL, '江戶川'),
('odpt:Station:TokyoMetro.Tozai.NishiFunabashi', false, NULL, '江戶川'),
('odpt:Station:Keisei.Kawabata', false, NULL, '江戶川'),
('odpt:Station:Keisei.Koiwa', false, NULL, '江戶川'),
('odpt:Station:JR-East.Shinmatsudo', false, NULL, '江戶川'),
('odpt:Station:TokyoMetro.Tozai.Shinmatsudo', false, NULL, '江戶川'),

-- === 涉谷區（Shibuya）===
('odpt:Station:JR-East.Shibuya', true, NULL, '涉谷'),
('odpt:Station:TokyoMetro.Ginza.Shibuya', false, 'odpt:Station:JR-East.Shibuya', '涉谷'),
('odpt:Station:TokyoMetro.Hanzomon.Shibuya', false, 'odpt:Station:JR-East.Shibuya', '涉谷'),
('odpt:Station:TokyoMetro.Fukutoshin.Shibuya', false, 'odpt:Station:JR-East.Shibuya', '涉谷'),
('odpt:Station:TokyoMetro.Yamanote.Shibuya', false, 'odpt:Station:JR-East.Shibuya', '涉谷'),
('odpt:Station:TokyuToyoko.Shibuya', false, 'odpt:Station:JR-East.Shibuya', '涉谷'),
('odpt:Station:TokyuDenEnToshi.Shibuya', false, 'odpt:Station:JR-East.Shibuya', '涉谷'),
('odpt:Station:KeioInokashira.Shibuya', false, 'odpt:Station:JR-East.Shibuya', '涉谷'),
('odpt:Station:JR-East.Harajuku', false, NULL, '涉谷'),
('odpt:Station:JR-East.YoyogiHachiman', false, NULL, '涉谷'),
('odpt:Station:JR-East.YoyogiUehara', false, NULL, '涉谷'),
('odpt:Station:TokyoMetro.Chiyoda.Omotesando', false, NULL, '涉谷'),
('odpt:Station:TokyoMetro.Hanzomon.Omotesando', false, NULL, '涉谷'),
('odpt:Station:TokyoMetro.Ginza.Omotesando', false, NULL, '涉谷'),
('odpt:Station:TokyoMetro.Fukutoshin.MeijiJingumae', false, NULL, '涉谷'),
('odpt:Station:JR-East.MeijiJingumae', false, NULL, '涉谷'),
('odpt:Station:TokyoMetro.Hibiya.NakanoSakaue', false, NULL, '涉谷'),
('odpt:Station:TokyoMetro.Namboku.NakanoSakaue', false, NULL, '涉谷'),
('odpt:Station:TokyoMetro.Hibiya.Shinjuku', false, NULL, '涉谷'),
('odpt:Station:TokyoMetro.Ginza.AoyamaItchome', false, NULL, '涉谷'),
('odpt:Station:TokyoMetro.Hanzomon.AoyamaItchome', false, NULL, '涉谷'),
('odpt:Station:TokyoMetro.Chiyoda.AoyamaItchome', false, NULL, '涉谷'),

-- === 中野區（Nakano）===
('odpt:Station:JR-East.Nakano', true, NULL, '中野'),
('odpt:Station:TokyoMetro.Hibiya.Nakano', false, 'odpt:Station:JR-East.Nakano', '中野'),
('odpt:Station:JR-East.Koenji', false, NULL, '中野'),
('odpt:Station:JR-East.ShinKoenji', false, NULL, '中野'),
('odpt:Station:TokyoMetro.Tozai.Nakano', false, NULL, '中野'),
('odpt:Station:JR-East.Honancho', false, NULL, '中野'),
('odpt:Station:JR-East.Saginomiya', false, NULL, '中野'),
('odpt:Station:SeibuShinjuku.Nakano', false, NULL, '中野'),
('odpt:Station:JR-East.Nakai', false, NULL, '中野');

-- === 更新資料庫 ===

-- Step 2: 將所有節點先重置為 Standalone
UPDATE nodes SET is_hub = false, parent_hub_id = NULL WHERE true;

-- Step 3: 更新 seed_hierarchy_tokyo_23wards 中的節點
UPDATE nodes n
SET
    is_hub = s.is_hub,
    parent_hub_id = s.parent_hub_id
FROM seed_hierarchy_tokyo_23wards s
WHERE n.id = s.node_id;

-- Step 4: 驗證結果 - 按區域分類
SELECT
    ward,
    COUNT(*) FILTER (WHERE is_hub = true) as hubs,
    COUNT(*) FILTER (WHERE is_hub = false AND parent_hub_id IS NULL) as standalone,
    COUNT(*) FILTER (WHERE parent_hub_id IS NOT NULL) as children,
    COUNT(*) as total
FROM nodes n
JOIN seed_hierarchy_tokyo_23wards s ON n.id = s.node_id
GROUP BY ward
ORDER BY ward;

-- Step 5: 驗證所有 Hub 站點
SELECT id, name->>'zh-TW' as name, is_hub, parent_hub_id
FROM nodes
WHERE is_hub = true
ORDER BY name->>'zh-TW';

-- Step 6: 統計總數
SELECT
    COUNT(*) FILTER (WHERE is_hub = true) as hubs,
    COUNT(*) FILTER (WHERE is_hub = false AND parent_hub_id IS NULL) as standalone,
    COUNT(*) FILTER (WHERE parent_hub_id IS NOT NULL) as children,
    COUNT(*) as total
FROM nodes
WHERE id IN (SELECT node_id FROM seed_hierarchy_tokyo_23wards);

-- Step 7: 驗證父子關係
SELECT
    p.name->>'zh-TW' as hub_name,
    c.name->>'zh-TW' as child_name,
    c.id as child_id
FROM nodes c
JOIN nodes p ON c.parent_hub_id = p.id
ORDER BY p.name->>'zh-TW', c.name->>'zh-TW';
