-- =============================================================================
-- Complete Fix: 東京23區所有車站父子節點修復 - 最終版
-- 使用安全插入方式處理重複 key 問題
-- =============================================================================

-- Step 1: 建立 seed 表（不使用 PRIMARY KEY 避免衝突）
DROP TABLE IF EXISTS seed_hierarchy_tokyo;
CREATE TEMP TABLE seed_hierarchy_tokyo (
    node_id TEXT,
    is_hub BOOLEAN,
    parent_hub_id TEXT
);

-- Step 2: 插入所有 seed 數據（每個 node_id 只出現一次）
INSERT INTO seed_hierarchy_tokyo (node_id, is_hub, parent_hub_id)

-- 千代田區
SELECT 'odpt:Station:JR-East.Tokyo', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Tokyo')
UNION ALL SELECT 'odpt:Station:JR-East.Kanda', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Kanda')
UNION ALL SELECT 'odpt:Station:JR-East.Iidabashi', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Iidabashi')
UNION ALL SELECT 'odpt:Station:JR-East.Ichigaya', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Ichigaya')
UNION ALL SELECT 'odpt:Station:JR-East.Kudanshita', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Kudanshita')
UNION ALL SELECT 'odpt:Station:JR-East.Yotsuya', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Yotsuya')
UNION ALL SELECT 'odpt:Station:JR-East.Suidobashi', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Suidobashi')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Otemachi', false, 'odpt:Station:JR-East.Tokyo' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Otemachi')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Chiyoda.Otemachi', false, 'odpt:Station:JR-East.Tokyo' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Chiyoda.Otemachi')
UNION ALL SELECT 'odpt:Station:Toei.Mita.Otemachi', false, 'odpt:Station:JR-East.Tokyo' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Mita.Otemachi')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Ginza.Kanda', false, 'odpt:Station:JR-East.Kanda' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Ginza.Kanda')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hibiya.Kanda', false, 'odpt:Station:JR-East.Kanda' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hibiya.Kanda')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Kanda', false, 'odpt:Station:JR-East.Kanda' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Kanda')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Iidabashi', false, 'odpt:Station:JR-East.Iidabashi' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Iidabashi')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Yurakucho.Iidabashi', false, 'odpt:Station:JR-East.Iidabashi' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Yurakucho.Iidabashi')
UNION ALL SELECT 'odpt:Station:Toei.Oedo.Iidabashi', false, 'odpt:Station:JR-East.Iidabashi' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Oedo.Iidabashi')
UNION ALL SELECT 'odpt:Station:Toei.Shinjuku.Ichigaya', false, 'odpt:Station:JR-East.Ichigaya' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Shinjuku.Ichigaya')
UNION ALL SELECT 'odpt:Station:Toei.Oedo.Ichigaya', false, 'odpt:Station:JR-East.Ichigaya' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Oedo.Ichigaya')
UNION ALL SELECT 'odpt:Station:Toei.Shinjuku.Kudanshita', false, 'odpt:Station:JR-East.Kudanshita' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Shinjuku.Kudanshita')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Tozai.Kudanshita', false, 'odpt:Station:JR-East.Kudanshita' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Tozai.Kudanshita')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hibiya', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hibiya')
UNION ALL SELECT 'odpt:Station:Toei.Mita.Hibiya', false, 'odpt:Station:TokyoMetro.Hibiya' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Mita.Hibiya')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Ginza', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Ginza')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hibiya.Ginza', false, 'odpt:Station:TokyoMetro.Ginza' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hibiya.Ginza')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Marunouchi', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Marunouchi')
UNION ALL SELECT 'odpt:Station:Toei.Jimbocho', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Jimbocho')
UNION ALL SELECT 'odpt:Station:Toei.Shinjuku.Jimbocho', false, 'odpt:Station:Toei.Jimbocho' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Shinjuku.Jimbocho')
UNION ALL SELECT 'odpt:Station:Toei.Ogawamachi', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Ogawamachi')
UNION ALL SELECT 'odpt:Station:Toei.Iwamotocho', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Iwamotocho')
UNION ALL SELECT 'odpt:Station:Toei.Uchisaiwaicho', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Uchisaiwaicho')
UNION ALL SELECT 'odpt:Station:Toei.Mita', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Mita')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Namboku.Mita', false, 'odpt:Station:Toei.Mita' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Namboku.Mita')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Kasumigaseki', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Kasumigaseki')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Chiyoda', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Chiyoda')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Nezu', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Nezu')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Sendagi', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Sendagi')
UNION ALL SELECT 'odpt:Station:TokyoMetro.NishiNippori', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.NishiNippori')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Yushima', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Yushima')
UNION ALL SELECT 'odpt:Station:TokyoMetro.ShinOchanomizu', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.ShinOchanomizu')
UNION ALL SELECT 'odpt:Station:TokyoMetro.KokkaiGijidomae', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.KokkaiGijidomae')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Nijubashimae', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Nijubashimae')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Akasaka', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Akasaka')
UNION ALL SELECT 'odpt:Station:TokyoMetro.AkasakaMitsuke', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.AkasakaMitsuke')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Nagatacho', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Nagatacho')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hanzomon', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hanzomon')

-- 中央區
UNION ALL SELECT 'odpt:Station:JR-East.Yurakucho', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Yurakucho')
UNION ALL SELECT 'odpt:Station:JR-East.Shimbashi', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Shimbashi')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Nihombashi', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Nihombashi')
UNION ALL SELECT 'odpt:Station:Toei.Asakusa.Nihombashi', false, 'odpt:Station:TokyoMetro.Nihombashi' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Asakusa.Nihombashi')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Kayabacho', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Kayabacho')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Ningyocho', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Ningyocho')
UNION ALL SELECT 'odpt:Station:Toei.Asakusa.Ningyocho', false, 'odpt:Station:TokyoMetro.Ningyocho' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Asakusa.Ningyocho')
UNION ALL SELECT 'odpt:Station:JR-East.Hatchobori', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Hatchobori')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hibiya.Hatchobori', false, 'odpt:Station:JR-East.Hatchobori' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hibiya.Hatchobori')
UNION ALL SELECT 'odpt:Station:TokyoMetro.HigashiGinza', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.HigashiGinza')
UNION ALL SELECT 'odpt:Station:JR-East.Tsukiji', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Tsukiji')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hibiya.Tsukiji', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hibiya.Tsukiji')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Yurakucho.Tsukishima', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Yurakucho.Tsukishima')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Yurakucho.Toyosu', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Yurakucho.Toyosu')
UNION ALL SELECT 'odpt:Station:JR-East.Toyosu', false, 'odpt:Station:TokyoMetro.Yurakucho.Toyosu' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Toyosu')
UNION ALL SELECT 'odpt:Station:JR-East.Shibaura', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Shibaura')
UNION ALL SELECT 'odpt:Station:JR-East.Hamamatsucho', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Hamamatsucho')
UNION ALL SELECT 'odpt:Station:Toei.Asakusa.Daimon', false, 'odpt:Station:JR-East.Hamamatsucho' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Asakusa.Daimon')
UNION ALL SELECT 'odpt:Station:TokyoMonorail.HanedaAirport.Hamamatsucho', false, 'odpt:Station:JR-East.Hamamatsucho' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMonorail.HanedaAirport.Hamamatsucho')
UNION ALL SELECT 'odpt:Station:JR-East.Tamachi', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Tamachi')

-- 港區
UNION ALL SELECT 'odpt:Station:JR-East.Shinagawa', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Shinagawa')
UNION ALL SELECT 'odpt:Station:Keikyu.Shinagawa', false, 'odpt:Station:JR-East.Shinagawa' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Keikyu.Shinagawa')
UNION ALL SELECT 'odpt:Station:JR-East.Yamanote.Shinagawa', false, 'odpt:Station:JR-East.Shinagawa' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Yamanote.Shinagawa')
UNION ALL SELECT 'odpt:Station:JR-East.KeihinTohoku.Shinagawa', false, 'odpt:Station:JR-East.Shinagawa' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.KeihinTohoku.Shinagawa')
UNION ALL SELECT 'odpt:Station:JR-East.Tokaido.Shinagawa', false, 'odpt:Station:JR-East.Shinagawa' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Tokaido.Shinagawa')
UNION ALL SELECT 'odpt:Station:JR-East.Yokosuka.Shinagawa', false, 'odpt:Station:JR-East.Shinagawa' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Yokosuka.Shinagawa')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Ginza.Akasaka', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Ginza.Akasaka')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Chiyoda.Akasaka', false, 'odpt:Station:TokyoMetro.Ginza.Akasaka' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Chiyoda.Akasaka')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Ginza.AkasakaMitsuke', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Ginza.AkasakaMitsuke')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Namboku.AkasakaMitsuke', false, 'odpt:Station:TokyoMetro.Ginza.AkasakaMitsuke' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Namboku.AkasakaMitsuke')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Chiyoda.AkasakaMitsuke', false, 'odpt:Station:TokyoMetro.Ginza.AkasakaMitsuke' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Chiyoda.AkasakaMitsuke')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hanzomon.AkasakaMitsuke', false, 'odpt:Station:TokyoMetro.Ginza.AkasakaMitsuke' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hanzomon.AkasakaMitsuke')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Ginza.AoyamaItchome', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Ginza.AoyamaItchome')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hanzomon.AoyamaItchome', false, 'odpt:Station:TokyoMetro.Ginza.AoyamaItchome' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hanzomon.AoyamaItchome')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Chiyoda.AoyamaItchome', false, 'odpt:Station:TokyoMetro.Ginza.AoyamaItchome' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Chiyoda.AoyamaItchome')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hibiya.Roppongi', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hibiya.Roppongi')
UNION ALL SELECT 'odpt:Station:Toei.Oedo.Roppongi', false, 'odpt:Station:TokyoMetro.Hibiya.Roppongi' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Oedo.Roppongi')
UNION ALL SELECT 'odpt:Station:Toei.Namboku.AzabuJuban', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Namboku.AzabuJuban')
UNION ALL SELECT 'odpt:Station:Toei.Mita.AzabuJuban', false, 'odpt:Station:Toei.Namboku.AzabuJuban' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Mita.AzabuJuban')
UNION ALL SELECT 'odpt:Station:JR-East.Ebisu', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Ebisu')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hibiya.Ebisu', false, 'odpt:Station:JR-East.Ebisu' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hibiya.Ebisu')
UNION ALL SELECT 'odpt:Station:JR-East.Meguro', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Meguro')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Namboku.Meguro', false, 'odpt:Station:JR-East.Meguro' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Namboku.Meguro')
UNION ALL SELECT 'odpt:Station:Toei.Mita.Meguro', false, 'odpt:Station:JR-East.Meguro' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Mita.Meguro')
UNION ALL SELECT 'odpt:Station:TokyuToyoko.Meguro', false, 'odpt:Station:JR-East.Meguro' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuToyoko.Meguro')
UNION ALL SELECT 'odpt:Station:JR-East.Yamanote.TakanawaGateway', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Yamanote.TakanawaGateway')
UNION ALL SELECT 'odpt:Station:TokyoMonorail.HanedaAirport.TennozuIsle', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMonorail.HanedaAirport.TennozuIsle')
UNION ALL SELECT 'odpt:Station:Keikyu.Sengakuji', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Keikyu.Sengakuji')
UNION ALL SELECT 'odpt:Station:Toei.Asakusa.Sengakuji', false, 'odpt:Station:Keikyu.Sengakuji' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Asakusa.Sengakuji')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Namboku.ShirokaneTakanawa', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Namboku.ShirokaneTakanawa')
UNION ALL SELECT 'odpt:Station:Toei.Mita.ShirokaneTakanawa', false, 'odpt:Station:TokyoMetro.Namboku.ShirokaneTakanawa' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Mita.ShirokaneTakanawa')
UNION ALL SELECT 'odpt:Station:Toei.Mita.Mita', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Mita.Mita')

-- 豐島區
UNION ALL SELECT 'odpt:Station:JR-East.Ikebukuro', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Ikebukuro')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Ikebukuro', false, 'odpt:Station:JR-East.Ikebukuro' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Ikebukuro')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Yurakucho.Ikebukuro', false, 'odpt:Station:JR-East.Ikebukuro' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Yurakucho.Ikebukuro')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Namboku.Ikebukuro', false, 'odpt:Station:JR-East.Ikebukuro' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Namboku.Ikebukuro')
UNION ALL SELECT 'odpt:Station:Seibu.Ikebukuro', false, 'odpt:Station:JR-East.Ikebukuro' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Seibu.Ikebukuro')
UNION ALL SELECT 'odpt:Station:JR-East.Komagome', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Komagome')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Namboku.Komagome', false, 'odpt:Station:JR-East.Komagome' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Namboku.Komagome')
UNION ALL SELECT 'odpt:Station:Toei.NipporiToneri.Komagome', false, 'odpt:Station:JR-East.Komagome' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.NipporiToneri.Komagome')
UNION ALL SELECT 'odpt:Station:JR-East.Sugamo', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Sugamo')
UNION ALL SELECT 'odpt:Station:JR-East.Otsuka', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Otsuka')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Yurakucho.Otsuka', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Yurakucho.Otsuka')
UNION ALL SELECT 'odpt:Station:JR-East.Mejiro', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Mejiro')
UNION ALL SELECT 'odpt:Station:JR-East.Shii', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Shii')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Yurakucho.Shinotsuka', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Yurakucho.Shinotsuka')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Yurakucho.Wakamatsukawara', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Yurakucho.Wakamatsukawara')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Tozai.Wakamatsukawara', false, 'odpt:Station:TokyoMetro.Yurakucho.Wakamatsukawara' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Tozai.Wakamatsukawara')

-- 涉谷區
UNION ALL SELECT 'odpt:Station:JR-East.Shibuya', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Shibuya')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Ginza.Shibuya', false, 'odpt:Station:JR-East.Shibuya' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Ginza.Shibuya')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hanzomon.Shibuya', false, 'odpt:Station:JR-East.Shibuya' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hanzomon.Shibuya')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Fukutoshin.Shibuya', false, 'odpt:Station:JR-East.Shibuya' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Fukutoshin.Shibuya')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Chiyoda.Shibuya', false, 'odpt:Station:JR-East.Shibuya' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Chiyoda.Shibuya')
UNION ALL SELECT 'odpt:Station:TokyuToyoko.Shibuya', false, 'odpt:Station:JR-East.Shibuya' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuToyoko.Shibuya')
UNION ALL SELECT 'odpt:Station:TokyuDenEnToshi.Shibuya', false, 'odpt:Station:JR-East.Shibuya' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuDenEnToshi.Shibuya')
UNION ALL SELECT 'odpt:Station:Keio.Shibuya', false, 'odpt:Station:JR-East.Shibuya' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Keio.Shibuya')
UNION ALL SELECT 'odpt:Station:JR-East.Harajuku', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Harajuku')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Chiyoda.Omotesando', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Chiyoda.Omotesando')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Ginza.Omotesando', false, 'odpt:Station:TokyoMetro.Chiyoda.Omotesando' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Ginza.Omotesando')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hanzomon.Omotesando', false, 'odpt:Station:TokyoMetro.Chiyoda.Omotesando' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hanzomon.Omotesando')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hibiya.Hiroo', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hibiya.Hiroo')
UNION ALL SELECT 'odpt:Station:TokyuToyoko.Daikanyama', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuToyoko.Daikanyama')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hibiya.NakaMeguro', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hibiya.NakaMeguro')
UNION ALL SELECT 'odpt:Station:TokyuToyoko.NakaMeguro', false, 'odpt:Station:TokyoMetro.Hibiya.NakaMeguro' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuToyoko.NakaMeguro')
UNION ALL SELECT 'odpt:Station:TokyuDenEnToshi.NakaMeguro', false, 'odpt:Station:TokyoMetro.Hibiya.NakaMeguro' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuDenEnToshi.NakaMeguro')
UNION ALL SELECT 'odpt:Station:Odakyu.YoyogiUehara', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Odakyu.YoyogiUehara')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Chiyoda.YoyogiUehara', false, 'odpt:Station:Odakyu.YoyogiUehara' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Chiyoda.YoyogiUehara')
UNION ALL SELECT 'odpt:Station:Keio.YoyogiUehara', false, 'odpt:Station:Odakyu.YoyogiUehara' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Keio.YoyogiUehara')
UNION ALL SELECT 'odpt:Station:JR-East.Yoyogi', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Yoyogi')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Chiyoda.YoyogiKoen', false, 'odpt:Station:JR-East.Yoyogi' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Chiyoda.YoyogiKoen')
UNION ALL SELECT 'odpt:Station:Toei.Oedo.Yoyogi', false, 'odpt:Station:JR-East.Yoyogi' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Oedo.Yoyogi')

-- 台東區
UNION ALL SELECT 'odpt:Station:JR-East.Ueno', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Ueno')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Ueno', false, 'odpt:Station:JR-East.Ueno' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Ueno')
UNION ALL SELECT 'odpt:Station:Keisei.Ueno', false, 'odpt:Station:JR-East.Ueno' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Keisei.Ueno')
UNION ALL SELECT 'odpt:Station:JR-East.Akihabara', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Akihabara')
UNION ALL SELECT 'odpt:Station:TsukubaExpress.Akihabara', false, 'odpt:Station:JR-East.Akihabara' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TsukubaExpress.Akihabara')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hibiya.Akihabara', false, 'odpt:Station:JR-East.Akihabara' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hibiya.Akihabara')
UNION ALL SELECT 'odpt:Station:JR-East.Okachimachi', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Okachimachi')
UNION ALL SELECT 'odpt:Station:JR-East.UenoOkachimachi', false, 'odpt:Station:JR-East.Okachimachi' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.UenoOkachimachi')
UNION ALL SELECT 'odpt:Station:TokyoMetro.NakaOkachimachi', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.NakaOkachimachi')
UNION ALL SELECT 'odpt:Station:JR-East.Uguisudani', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Uguisudani')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Inaricho', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Inaricho')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Iriya', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Iriya')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Minowa', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Minowa')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Tawaramachi', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Tawaramachi')
UNION ALL SELECT 'odpt:Station:Toei.Kuramae', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Kuramae')
UNION ALL SELECT 'odpt:Station:Toei.Asakusabashi', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Asakusabashi')
UNION ALL SELECT 'odpt:Station:Toei.ShinOkachimachi', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.ShinOkachimachi')
UNION ALL SELECT 'odpt:Station:Toei.HigashiNihombashi', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.HigashiNihombashi')
UNION ALL SELECT 'odpt:Station:Toei.BakuroYokoyama', false, 'odpt:Station:Toei.HigashiNihombashi' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.BakuroYokoyama')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Asakusa', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Asakusa')
UNION ALL SELECT 'odpt:Station:Toei.Asakusa.Asakusa', false, 'odpt:Station:TokyoMetro.Asakusa' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Asakusa.Asakusa')
UNION ALL SELECT 'odpt:Station:Tobu.Asakusa', false, 'odpt:Station:TokyoMetro.Asakusa' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Tobu.Asakusa')
UNION ALL SELECT 'odpt:Station:TsukubaExpress.Asakusa', false, 'odpt:Station:TokyoMetro.Asakusa' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TsukubaExpress.Asakusa')
UNION ALL SELECT 'odpt:Station:Toei.Oedo.UenoOkachimachi', false, 'odpt:Station:JR-East.Ueno' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Oedo.UenoOkachimachi')
UNION ALL SELECT 'odpt:Station:Toei.Oedo.ShinOkachimachi', false, 'odpt:Station:Toei.ShinOkachimachi' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Oedo.ShinOkachimachi')
UNION ALL SELECT 'odpt:Station:Toei.Oedo.UshigomeYanagicho', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Oedo.UshigomeYanagicho')

-- 新宿區
UNION ALL SELECT 'odpt:Station:JR-East.Shinjuku', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Shinjuku')
UNION ALL SELECT 'odpt:Station:JR-East.SeibuShinjuku', false, 'odpt:Station:JR-East.Shinjuku' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.SeibuShinjuku')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Shinjuku', false, 'odpt:Station:JR-East.Shinjuku' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Shinjuku')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hibiya.Shinjuku', false, 'odpt:Station:JR-East.Shinjuku' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hibiya.Shinjuku')
UNION ALL SELECT 'odpt:Station:Toei.Shinjuku.Shinjuku', false, 'odpt:Station:JR-East.Shinjuku' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Shinjuku.Shinjuku')
UNION ALL SELECT 'odpt:Station:Keio.Shinjuku', false, 'odpt:Station:JR-East.Shinjuku' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Keio.Shinjuku')
UNION ALL SELECT 'odpt:Station:Odakyu.Shinjuku', false, 'odpt:Station:JR-East.Shinjuku' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Odakyu.Shinjuku')
UNION ALL SELECT 'odpt:Station:JR-East.Shidaya', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Shidaya')
UNION ALL SELECT 'odpt:Station:JR-East.Ōkubo', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Ōkubo')
UNION ALL SELECT 'odpt:Station:JR-East.HigashiNakano', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.HigashiNakano')
UNION ALL SELECT 'odpt:Station:JR-East.Kochi', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Kochi')
UNION ALL SELECT 'odpt:Station:JR-East.Sakura', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Sakura')
UNION ALL SELECT 'odpt:Station:TokyoMetro.NishiShinjuku', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.NishiShinjuku')
UNION ALL SELECT 'odpt:Station:Toei.Oedo.NishiShinjuku', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Oedo.NishiShinjuku')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Tozai.Waseda', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Tozai.Waseda')
UNION ALL SELECT 'odpt:Station:Toei.Shinjuku.Kagurazaka', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Shinjuku.Kagurazaka')
UNION ALL SELECT 'odpt:Station:Toei.Oedo.UshigomeKagurazaka', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Oedo.UshigomeKagurazaka')
UNION ALL SELECT 'odpt:Station:JR-East.Takadanobaba', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Takadanobaba')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hibiya.Takadanobaba', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hibiya.Takadanobaba')
UNION ALL SELECT 'odpt:Station:SeibuShinjuku.Takadanobaba', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:SeibuShinjuku.Takadanobaba')

-- 文京區
UNION ALL SELECT 'odpt:Station:JR-East.HongoSanchome', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.HongoSanchome')
UNION ALL SELECT 'odpt:Station:TokyoMetro.HongoSanchome', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.HongoSanchome')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Korakuen', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Korakuen')
UNION ALL SELECT 'odpt:Station:TokyoMetro.ShinOchanomizu', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.ShinOchanomizu')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Ochanomizu', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Ochanomizu')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Kasuga', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Kasuga')
UNION ALL SELECT 'odpt:Station:Toei.Mita.Kasuga', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Mita.Kasuga')
UNION ALL SELECT 'odpt:Station:Toei.Oedo.Kasuga', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Oedo.Kasuga')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Myogadani', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Myogadani')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Shinotsuka', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Shinotsuka')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Kawaguchi', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Kawaguchi')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Awajicho', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Awajicho')

-- 江東區
UNION ALL SELECT 'odpt:Station:TokyoMetro.Tozai.Nihombashi', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Tozai.Nihombashi')
UNION ALL SELECT 'odpt:Station:Toei.Shinjuku.BakuroYokoyama', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Shinjuku.BakuroYokoyama')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hibiya.Kodemmacho', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hibiya.Kodemmacho')
UNION ALL SELECT 'odpt:Station:Toei.Shinjuku.Hamacho', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Shinjuku.Hamacho')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Tozai.MonzenNakacho', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Tozai.MonzenNakacho')
UNION ALL SELECT 'odpt:Station:Toei.Oedo.MonzenNakacho', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Oedo.MonzenNakacho')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Tozai.Kiba', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Tozai.Kiba')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hanzomon.Suitengumae', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hanzomon.Suitengumae')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hanzomon.KiyosumiShirakawa', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hanzomon.KiyosumiShirakawa')
UNION ALL SELECT 'odpt:Station:Toei.Oedo.Tsukijishijo', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Oedo.Tsukijishijo')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Yurakucho.Shintomicho', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Yurakucho.Shintomicho')
UNION ALL SELECT 'odpt:Station:JR-East.Shintomi', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Shintomi')
UNION ALL SELECT 'odpt:Station:Toei.Oedo.Kachidoki', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Toei.Oedo.Kachidoki')

-- 品川區
UNION ALL SELECT 'odpt:Station:JR-East.Kita-Shinagawa', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Kita-Shinagawa')
UNION ALL SELECT 'odpt:Station:JR-East.Osaki', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Osaki')
UNION ALL SELECT 'odpt:Station:JR-East.Magome', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Magome')
UNION ALL SELECT 'odpt:Station:JR-East.NishiOi', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.NishiOi')
UNION ALL SELECT 'odpt:Station:JR-East.Oi', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Oi')
UNION ALL SELECT 'odpt:Station:JR-East.Takanawa', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Takanawa')

-- 目黑區
UNION ALL SELECT 'odpt:Station:JR-East.Nakano', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Nakano')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hibiya.Nakano', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hibiya.Nakano')
UNION ALL SELECT 'odpt:Station:JR-East.Sakuragawa', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Sakuragawa')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Namboku.Sakuragawa', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Namboku.Sakuragawa')
UNION ALL SELECT 'odpt:Station:JR-East.GakugeiDaigaku', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.GakugeiDaigaku')
UNION ALL SELECT 'odpt:Station:TokyuToyoko.GakugeiDaigaku', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuToyoko.GakugeiDaigaku')
UNION ALL SELECT 'odpt:Station:JR-East.ToritsuDaigaku', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.ToritsuDaigaku')
UNION ALL SELECT 'odpt:Station:TokyuToyoko.ToritsuDaigaku', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuToyoko.ToritsuDaigaku')
UNION ALL SELECT 'odpt:Station:JR-East.Jiyugaoka', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Jiyugaoka')
UNION ALL SELECT 'odpt:Station:TokyuToyoko.Jiyugaoka', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuToyoko.Jiyugaoka')
UNION ALL SELECT 'odpt:Station:TokyuDenEnToshi.DenEnToshi', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuDenEnToshi.DenEnToshi')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Hibiya.NakanoSakaue', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Hibiya.NakanoSakaue')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Namboku.NakanoSakaue', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Namboku.NakanoSakaue')

-- 大田区
UNION ALL SELECT 'odpt:Station:JR-East.Omori', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Omori')
UNION ALL SELECT 'odpt:Station:JR-East.Kamata', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Kamata')
UNION ALL SELECT 'odpt:Station:JR-East.Heiwajima', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Heiwajima')
UNION ALL SELECT 'odpt:Station:JR-East.Otorii', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Otorii')
UNION ALL SELECT 'odpt:Station:JR-East.HanedaAirport', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.HanedaAirport')
UNION ALL SELECT 'odpt:Station:TokyoMonorail.HanedaAirport', false, 'odpt:Station:JR-East.HanedaAirport' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMonorail.HanedaAirport')
UNION ALL SELECT 'odpt:Station:Keikyu.HanedaAirport', false, 'odpt:Station:JR-East.HanedaAirport' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Keikyu.HanedaAirport')
UNION ALL SELECT 'odpt:Station:JR-East.Tsutsumi', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Tsutsumi')
UNION ALL SELECT 'odpt:Station:TokyuIkegaya.Tsutsujigaoka', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuIkegaya.Tsutsujigaoka')
UNION ALL SELECT 'odpt:Station:JR-East.Fussa', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Fussa')
UNION ALL SELECT 'odpt:Station:JR-East.Daikanyama', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Daikanyama')

-- 世田谷區
UNION ALL SELECT 'odpt:Station:TokyuToyoko.SetagayaDaita', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuToyoko.SetagayaDaita')
UNION ALL SELECT 'odpt:Station:TokyuToyoko.DaisanShinkawa', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuToyoko.DaisanShinkawa')
UNION ALL SELECT 'odpt:Station:TokyuToyoko.Sangenjaya', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuToyoko.Sangenjaya')
UNION ALL SELECT 'odpt:Station:TokyuDenEnToshi.Sangenjaya', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuDenEnToshi.Sangenjaya')
UNION ALL SELECT 'odpt:Station:TokyuDenEnToshi.ComimaHongo', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuDenEnToshi.ComimaHongo')
UNION ALL SELECT 'odpt:Station:TokyuDenEnToshi.Kuhonbutsu', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuDenEnToshi.Kuhonbutsu')
UNION ALL SELECT 'odpt:Station:TokyuDenEnToshi.Yutenji', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuDenEnToshi.Yutenji')
UNION ALL SELECT 'odpt:Station:TokyuToyoko.Yutenji', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuToyoko.Yutenji')
UNION ALL SELECT 'odpt:Station:TokyuDenEnToshi.FutakoTamagawa', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuDenEnToshi.FutakoTamagawa')
UNION ALL SELECT 'odpt:Station:Odakyu.FutakoTamagawa', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Odakyu.FutakoTamagawa')
UNION ALL SELECT 'odpt:Station:TokyuDenEnToshi.Kamimachi', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuDenEnToshi.Kamimachi')
UNION ALL SELECT 'odpt:Station:TokyuDenEnToshi.Matsubara', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyuDenEnToshi.Matsubara')
UNION ALL SELECT 'odpt:Station:Odakyu.Kyodo', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Odakyu.Kyodo')
UNION ALL SELECT 'odpt:Station:Odakyu.Yurioka', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Odakyu.Yurioka')
UNION ALL SELECT 'odpt:Station:JR-East.Shimokitazawa', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Shimokitazawa')
UNION ALL SELECT 'odpt:Station:Odakyu.Setagaya', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Odakyu.Setagaya')
UNION ALL SELECT 'odpt:Station:Odakyu.Shimokitazawa', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:Odakyu.Shimokitazawa')

-- 杉並區
UNION ALL SELECT 'odpt:Station:JR-East.Asagaya', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Asagaya')
UNION ALL SELECT 'odpt:Station:JR-East.Kichijoji', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Kichijoji')
UNION ALL SELECT 'odpt:Station:JR-East.NishiOgikubo', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.NishiOgikubo')
UNION ALL SELECT 'odpt:Station:JR-East.Ogikubo', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Ogikubo')
UNION ALL SELECT 'odpt:Station:JR-East.Sakuradai', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Sakuradai')
UNION ALL SELECT 'odpt:Station:JR-East.MinamiAsagaya', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.MinamiAsagaya')
UNION ALL SELECT 'odpt:Station:JR-East.Honancho', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Honancho')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Marunouchi.HongoSanchome', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Marunouchi.HongoSanchome')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Marunouchi.Kokuryo', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Marunouchi.Kokuryo')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Marunouchi.NishiOgikubo', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Marunouchi.NishiOgikubo')
UNION ALL SELECT 'odpt:Station:SeibuShinjuku.Numabukuro', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:SeibuShinjuku.Numabukuro')
UNION ALL SELECT 'odpt:Station:SeibuShinjuku.Ikebukuro', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:SeibuShinjuku.Ikebukuro')
UNION ALL SELECT 'odpt:Station:SeibuChichibu.NishiOgikubo', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:SeibuChichibu.NishiOgikubo')

-- 北區
UNION ALL SELECT 'odpt:Station:JR-East.Akabane', true, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Akabane')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Namboku.Akabane', false, 'odpt:Station:JR-East.Akabane' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.Namboku.Akabane')
UNION ALL SELECT 'odpt:Station:TokyoMetro.SaitamaRailway.Akabane', false, 'odpt:Station:JR-East.Akabane' WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:TokyoMetro.SaitamaRailway.Akabane')
UNION ALL SELECT 'odpt:Station:JR-East.MinamiUrawa', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.MinamiUrawa')
UNION ALL SELECT 'odpt:Station:JR-East.Urawa', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Urawa')
UNION ALL SELECT 'odpt:Station:JR-East.HigashiKawaguchi', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.HigashiKawaguchi')
UNION ALL SELECT 'odpt:Station:JR-East.Kawaguchi', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Kawaguchi')
UNION ALL SELECT 'odpt:Station:JR-East.NishiKawaguchi', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.NishiKawaguchi')
UNION ALL SELECT 'odpt:Station:JR-East.Hatagaya', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Hatagaya')
UNION ALL SELECT 'odpt:Station:JR-East.Tabata', false, NULL WHERE NOT EXISTS (SELECT 1 FROM seed_hierarchy_tokyo WHERE node_id = 'odpt:Station:JR-East.Tabata')
UNION ALL SELECT 'odpt:Station:TokyoMetro.Namb
